### ISSUE TITLE
undefined error in style-prop-object

### ISSUE THREAD

**Issue by kouhin** [yannickcr/eslint-plugin-react#824] opened 2016-09-13 07:08 UTC
```
> eslint 'src/**/*.js'

The react/require-extension rule is deprecated. Please use the import/extensions rule from eslint-plugin-import instead.
Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at /Users/myabc/git/myproj/node_modules/eslint-plugin-react/lib/rules/style-prop-object.js:51:34
    at Array.find (native)
    at EventEmitter.CallExpression (/Users/myabc/git/myproj/node_modules/eslint-plugin-react/lib/rules/style-prop-object.js:50:54)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at NodeEventGenerator.enterNode (/Users/myabc/git/myproj/node_modules/eslint/lib/util/node-event-generator.js:40:22)
    at CodePathAnalyzer.enterNode (/Users/myabc/git/myproj/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:23)
    at CommentEventGenerator.enterNode (/Users/myabc/git/myproj/node_modules/eslint/lib/util/comment-event-generator.js:97:23)
    at Controller.enter (/Users/myabc/git/myproj/node_modules/eslint/lib/eslint.js:918:36)
    at Controller.__execute (/Users/myabc/git/myproj/node_modules/estraverse/estraverse.js:397:31)
```

VERSION: 
```
    "eslint": "^3.3.0",
    "eslint-config-airbnb": "^11.1.0",
    "eslint-plugin-babel": "^3.3.0",
    "eslint-plugin-import": "^1.14.0",
    "eslint-plugin-jsx-a11y": "^2.2.2",
    "eslint-plugin-react": "^6.2.1",
```

**Comment by ljharb** [comment] 2016-09-13 07:17
What's the code this is erroring out on?

**Comment by ljharb** [comment] 2016-09-13 07:17
@kouhin either way, `eslint-config-airbnb` v11.1 requires eslint v3.5, and you have 3.3 - `npm ls` is likely reporting an error.

**Comment by kouhin** [comment] 2016-09-13 07:24
@ljharb Thanks. I will try to fix the required version. 

[This error](https://github.com/yannickcr/eslint-plugin-react/issues/821) occurs for every CI builds just from today, so I updated the deps by npm-check-updates('ncu -a -u'), and we got the style-prop-object error.

**Comment by kouhin** [comment] 2016-09-13 07:30
Sorry that I've made a mistake. Maybe ncu haven't updated all the packages.
I'll fix the version and try again.

**Comment by ljharb** [comment] 2016-09-13 07:34
For a package like `eslint-config-airbnb` that has peer dependencies, you should be updating manually.

**Comment by kouhin** [comment] 2016-09-15 10:23
@ljharb @yannickcr 

Error pattern: 

```
export class CustomLayout extends React.Component {
  static propTypes = {
    children: React.PropTypes.node,
    elementType: React.PropTypes.oneOf(['ul', 'div']),
  };

  render() {
    const { children, ...restProps } = this.props;
    return React.createElement(
      this.props.elementType,
      {
       ref: node => (this.dom = node),
        ...restProps,
      },
      this.props.children
    );
  }
}
```

**Comment by lencioni** [comment] 2016-09-16 16:46
@petersendidit Any chance you can look into this? Might be similar to #820

**Comment by lencioni** [comment] 2016-09-16 16:48
I think this is a duplicate of #809. Closing this issue in favor of that one.

**Closed by lencioni** 2016-09-16 16:48 UTC
Labels: bug
