### ISSUE TITLE
Rule Proposal: check for extraneous prop-types

### ISSUE THREAD

**Issue by luiscarli** [yannickcr/eslint-plugin-react#294] opened 2015-11-05 16:27 UTC
It may be interesting to have a rule that is the opposite of 'react/prop-types', a rule that check if there's prop-types declared which are not used during the render.

**Comment by atomanyih** [comment] 2015-11-09 18:58
https://github.com/yannickcr/eslint-plugin-react/issues/226

**Comment by yannickcr** [comment] 2015-11-16 22:52
Yep, duplicate of #226.

**Closed by yannickcr** 2015-11-16 22:52 UTC
Labels: new rule
