### ISSUE TITLE
Bug with v2.6.0

### ISSUE THREAD

**Issue by AlexKVal** [yannickcr/eslint-plugin-react#131] opened 2015-06-28 18:28 UTC
`eslint@0.24.0`
`node -v => v0.12.1`
```
> react-bootstrap@0.23.5 lint /Users/alexkval/src/js/react-bootstrap
> eslint ./

/Users/alexkval/src/js/react-bootstrap/node_modules/eslint-plugin-react/lib/rules/prop-types.js:536
      if (node.init.type !== 'ThisExpression' || node.id.type !== 'ObjectPatte
                   ^
TypeError: Cannot read property 'type' of null
    at EventEmitter.VariableDeclarator (/Users/alexkval/src/js/react-bootstrap/node_modules/eslint-plugin-react/lib/rules/prop-types.js:536:20)
    at EventEmitter.emit (events.js:129:20)
    at Controller.controller.traverse.enter (/Users/alexkval/src/js/react-bootstrap/node_modules/eslint/lib/eslint.js:724:25)
    at Controller.__execute (/Users/alexkval/src/js/react-bootstrap/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/Users/alexkval/src/js/react-bootstrap/node_modules/eslint/node_modules/estraverse/estraverse.js:495:28)
    at EventEmitter.module.exports.api.verify (/Users/alexkval/src/js/react-bootstrap/node_modules/eslint/lib/eslint.js:717:24)
    at processText (/Users/alexkval/src/js/react-bootstrap/node_modules/eslint/lib/cli-engine.js:201:27)
    at processFile (/Users/alexkval/src/js/react-bootstrap/node_modules/eslint/lib/cli-engine.js:226:12)
    at /Users/alexkval/src/js/react-bootstrap/node_modules/eslint/lib/cli-engine.js:322:26
    at /Users/alexkval/src/js/react-bootstrap/node_modules/eslint/lib/util/traverse.js:61:17
    at Array.forEach (native)
    at traverse (/Users/alexkval/src/js/react-bootstrap/node_modules/eslint/lib/util/traverse.js:41:54)
    at /Users/alexkval/src/js/react-bootstrap/node_modules/eslint/lib/util/traverse.js:63:17
    at Array.forEach (native)
    at traverse (/Users/alexkval/src/js/react-bootstrap/node_modules/eslint/lib/util/traverse.js:41:54)
    at walk (/Users/alexkval/src/js/react-bootstrap/node_modules/eslint/lib/util/traverse.js:83:9)
    at /Users/alexkval/src/js/react-bootstrap/node_modules/eslint/lib/util/traverse.js:102:9
    at Array.forEach (native)
    at traverse (/Users/alexkval/src/js/react-bootstrap/node_modules/eslint/lib/util/traverse.js:101:11)
    at CLIEngine.executeOnFiles (/Users/alexkval/src/js/react-bootstrap/node_modules/eslint/lib/cli-engine.js:313:9)
    at Object.cli.execute (/Users/alexkval/src/js/react-bootstrap/node_modules/eslint/lib/cli.js:179:95)
    at Object.<anonymous> (/Users/alexkval/src/js/react-bootstrap/node_modules/eslint/bin/eslint.js:32:20)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by yannickcr** [comment] 2015-06-28 18:29
Too slow ;)

Duplicate of #130

**Closed by yannickcr** 2015-06-28 18:29 UTC

**Comment by AlexKVal** [comment] 2015-06-28 18:34
Oh... I'm sorry :blush: 
:cherries:

**Comment by yannickcr** [comment] 2015-06-28 18:38
No problem, I'm happy to have some so-up-to-date persons to catch my bugs ;)
