### ISSUE TITLE
jsx-indent on lines with JSX expressions

### ISSUE THREAD

**Issue by NiGhTTraX** [yannickcr/eslint-plugin-react#1176] opened 2017-05-07 12:28 UTC
```jsx
const Item = ({ id, name, onSelect }) => <div onClick={onSelect}>
  {id}: {name}
</div>;
```

reports

```
Expected indentation of 2 space characters but found 0
```

It also complains about multiple variations:

JSX | Error
------|-------
`{name} foobar` | Expected indentation of 2 space characters but found 1 (react/jsx-indent)
`{id}: {name}` | Expected indentation of 2 space characters but found 0 (react/jsx-indent)
`{id} - {name}` | Expected indentation of 2 space characters but found 1 (react/jsx-indent)
`{id}. {name}` | Expected indentation of 2 space characters but found 0 (react/jsx-indent)
`{id} {name}` | No error
`{id}[2 spaces here]{name}` | Multiple spaces found before '{'  (no-multi-spaces) <- unrelated
`{id}[line break here]{name}` | No error
`{id}{name}` | No error

**Comment by ljharb** [comment] 2017-05-07 19:12
What about if you have explicit whitespace instead?:
```jsx
const Item = ({ id, name, onSelect }) => (
  <div onClick={onSelect}>
    {id}
    {': '}
    {name}
  </div>
);
```

**Comment by NiGhTTraX** [comment] 2017-05-13 20:45
@ljharb yes, that works, but it's not something I'd like to do.

**Comment by ljharb** [comment] 2017-05-13 20:58
Thanks for clarifying.

While it's decidely a best practice to make whitespace explicit instead of relying on jsx to handle it intuitively, your original case is clearly a bug.

**Comment by golopot** [comment] 2019-03-17 09:26
I cannot reproduce this. Seemed to be fixed.

**Comment by ljharb** [comment] 2019-03-17 17:38
If so, we can close this with a PR containing the test case.

**Comment by ljharb** [comment] 2022-02-04 00:42
@golopot the test case seems to fail, so this still seems like an issue.

**Closed** 2022-02-04 00:43 UTC
Labels: bug, help wanted
