### ISSUE TITLE
BUG:: false positive react/no-unused-prop-types

### ISSUE THREAD

**Issue by sagiavinash** [yannickcr/eslint-plugin-react#944] opened 2016-11-06 18:07 UTC
in following scenarios react/no-unused-prop-types is triggered falsely

1. if a particular prop is only accessed via `nextProps` then its not being considered as usage
  - in my use case i am referring in `componentWillReceiveProps(nextProps)`
2. sometimes if a prop is read only via es6 destructuring then its not being considered as usage
  - `const { dataPoint } = this.props;`
3. if a prop is referred inside a array.map callback then usage is not detected.

**Comment by tiemevanveen** [comment] 2016-11-15 13:08
Duplicate of at least https://github.com/yannickcr/eslint-plugin-react/issues/811 (your 1.) https://github.com/yannickcr/eslint-plugin-react/issues/814 (your 1.) and https://github.com/yannickcr/eslint-plugin-react/issues/819 (your 3.)

**Comment by DianaSuvorova** [comment] 2017-07-28 20:40
First 2 are fixed. For the 3rd there are nuances.But the simplest array.map use cases are supported Need to close this ticket. Thanks!

**Closed** 2017-07-28 21:16 UTC
