### ISSUE TITLE
no-unused-vars and no-undef don't work correctly when assigning JSX to variables

### ISSUE THREAD

**Issue by lencioni** [yannickcr/eslint-plugin-react#31] opened 2015-03-25 00:03 UTC
The following code:

```jsx
const React = require('react/addons');
const Things = require('react-router');

const { Thing, AnotherThing } = Things;

const stuff = (
  <Thing>
    <AnotherThing />
  </Thing>
);

const Test = React.createClass({
  render: function() {
    return stuff;
  }
});

module.exports = Test;
```

Generates the following messages:

```
4:8   error  Thing is defined but never used         no-unused-vars
4:15  error  AnotherThing is defined but never used  no-unused-vars
7:3   error  'Thing' is not defined                  no-undef
8:5   error  'AnotherThing' is not defined           no-undef
```

But this code is clean:

```jsx
const React = require('react/addons');
const Things = require('react-router');

const { Thing, AnotherThing } = Things;

const Test = React.createClass({
  render: function() {
    return (
      <Thing>
        <AnotherThing />
      </Thing>
    );
  }
});

module.exports = Test;
```

ESLint 0.17.1, eslint-plugin-react 1.6.0, with the following config:

```yaml
react/jsx-uses-react: 1
react/jsx-uses-vars: 1
react/react-in-jsx-scope: 1
```

**Comment by yannickcr** [comment] 2015-03-25 00:28
Duplicate of #18 and #19

**Closed by yannickcr** 2015-03-25 00:28 UTC
