### ISSUE TITLE
Error in react/no-danger-with-children with spread operator

### ISSUE THREAD

**Issue by poupourabou** [yannickcr/eslint-plugin-react#778] opened 2016-08-18 09:36 UTC
With eslint-plugin-react (6.1.1), an error occurs in this case : 

```
import React from 'react';
import Action from './action';

var Activity = React.createClass(
    {
        render : function () {
            var cont = this.compute();
            return (
                <div>
                    <Action
                        {...cont}
                    />
                </div>
            )
        },
        compute: function () {
            return {};
        }
    }
);

export default Activity;
```

Error : 
```
Cannot read property 'find' of undefined
TypeError: Cannot read property 'find' of undefined
    at findObjectProp (D:\path\node_modules\eslint-plugin-react\lib\rules\no-danger-with-children.js:28:29)
    at D:\path\node_modules\eslint-plugin-react\lib\rules\no-danger-with-children.js:46:20
    at Array.find (native)
    at findJsxProp (D:\path\node_modules\eslint-plugin-react\lib\rules\no-danger-with-children.js:40:25)
    at EventEmitter.JSXElement (D:\path\node_modules\eslint-plugin-react\lib\rules\no-danger-with-children.js:59:20)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.enterNode (D:\path\node_modules\eslint\lib\util\node-event-generator.js:40:22)
    at CodePathAnalyzer.enterNode (D:\path\node_modules\eslint\lib\code-path-analysis\code-path-analyzer.js:608:23)
    at CommentEventGenerator.enterNode (D:\path\node_modules\eslint\lib\util\comment-event-generator.js:97:23)

```

If **cont** is not the result of a function, there's no error.

**Comment by petersendidit** [comment] 2016-08-18 14:26
This is a duplicate of #771 which was fixed by #773 that was released in 6.1.2

**Closed** 2016-08-18 16:54 UTC
