### ISSUE TITLE
PropTypes.shape with error

### ISSUE THREAD

**Issue by learning** [yannickcr/eslint-plugin-react#823] opened 2016-09-13 03:54 UTC
I have something like this

```javascript
import React, { PropTypes } from 'react';

function Summary({index, day }) {
  return (
    <li>
      <h3>{index + 1}</h3>
      <p>{day.todos.map(todo => todo.title).join(',')}</p>
    </li>
  );
}

Summary.propTypes = {
  index: PropTypes.number,
  day: PropTypes.shape({
    todos: PropTypes.arrayOf(PropTypes.shape({
      title: PropTypes.string,
    })),
  }),
};
```

when I run lint, I got this error.

```bash
**:**  error  'day.todos' PropType is defined but prop is never used            react/no-unused-prop-types
**:**  error  'day.todos.*.title' PropType is defined but prop is never used    react/no-unused-prop-types
```

**Comment by zerkms** [comment] 2016-09-14 05:07
Relevant (or a duplicate?): https://github.com/yannickcr/eslint-plugin-react/issues/816

**Comment by EvNaverniouk** [comment] 2016-09-30 22:52
Duplicate of #871. 

The `no-unused-prop-types` rule does not support `shape` props at the moment as such detection is very difficult. If you use shape props, I recommend setting the `skipShapeProps` option to `true` on the rule.

**Closed** 2016-10-01 18:17 UTC
Labels: bug
