### ISSUE TITLE
Definition for rule 'react/state-in-constructor' was not found

### ISSUE THREAD

**Issue by kurtgn** [yannickcr/eslint-plugin-react#2174] opened 2019-02-22 06:53 UTC
I have a rule in my `.eslintrc`:

    "react/state-in-constructor": [2, "always"]

my eslint version is 7.12.4:

    npm list -g | grep eslint-plugin-react
    ├─┬ eslint-plugin-react@7.12.4

however eslint is unable to find this rule:

      1:1  error  Definition for rule 'react/state-in-constructor' was not found  react/state-in-constructor

how do I plug this rule in?

**Comment by ljharb** [comment] 2019-02-22 07:02
Have `eslint-plugin-react` installed, and somewhere in your config, have `'react'` in the `plugins` array.

**Comment by alexzherdev** [comment] 2019-02-22 07:10
Wait, I think this is a rule we haven’t released yet 😄

**Comment by ljharb** [comment] 2019-02-22 07:52
oh, oops :-) in that case, it's a duplicate of #2162, and you'll have to wait for a release.

**Closed by ljharb** 2019-02-22 07:52 UTC

**Comment by willklein** [comment] 2019-03-15 17:27
This just bit me... do we ever mark rules as unreleased in the README? Would we be open to that?

**Comment by ljharb** [comment] 2019-03-15 17:40
@willklein no - you shouldn’t be reading master, you should be reading the version tag that you have installed.

**Comment by willklein** [comment] 2019-03-15 20:37
Cool, that's a good point. I have this terrible habit of referring to READMEs on GitHub as the documentation. _Not_ being sarcastic, it's just my tendency.

**Comment by ljharb** [comment] 2019-03-15 21:16
Totally understood, we all do it :-) just train yourself whenever you see something that seems weird, to actually go drill down to the proper version tag
