### ISSUE TITLE
Destructuring values from props is not recognized by proptypes inside PropTypes.shape

### ISSUE THREAD

**Issue by GreenGeorge** [yannickcr/eslint-plugin-react#851] opened 2016-09-18 11:09 UTC
This is similar to #782 which actually works properly for me, what doesn't work is when the proptypes are inside shape() :

```javascript
const Person = ({ person }) =>
  <h1>{ person.name }</h1>;
```

```javascript
Person.propTypes = {
  person = React.PropTypes.shape({
    name: React.PropTypes.string, 
    // eslint error 'person.name' PropType is defined but prop is never used
    // error also pops up on stateful components
  }),
};
```

It works fine when i dont destructure
```javascript
const Person = props =>
  <h1>{ props.person.name }</h1>;  // no eslint error
```

**Comment by batjko** [comment] 2016-09-27 13:03
Just found the same issue.
But it still won't work if I replace the destructuring of the function argument, e.g.:
![image](https://cloud.githubusercontent.com/assets/7287076/18874797/0a5858b8-84bb-11e6-9304-716fc4ea4859.png)

(Before that, I just used `function SideMenuItems({menuItems})` instead. Same lint errors)

**Comment by EvNaverniouk** [comment] 2016-10-01 18:20
The `no-unused-prop-types` rule does not support `shape` props at the moment as such detection is very difficult. If you use shape props, I recommend setting the `skipShapeProps` option to `true` on the rule.

Duplicate of #819. Will track further discussion of `shape` props there.

**Closed by EvNaverniouk** 2016-10-01 18:20 UTC
Labels: bug
