### ISSUE TITLE
Spreading props fails linting with TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by josephmarkus** [yannickcr/eslint-plugin-react#2810] opened 2020-09-30 13:00 UTC
I bumped eslint-plugin-react from 7.20.6 to 7.21.2 and running lint fails with an unclear message.

I debugged below with line by line until I realised that `...props` spread fails linter.

```
Oops! Something went wrong! :(

ESLint: 7.10.0

TypeError: Cannot read property 'type' of undefined

Occurred while linting /Users/[...]/index.jsx:2
    at /Users/[...]/node_modules/eslint-plugin-react/lib/rules/prop-types.js:156:39
    at Array.forEach (<anonymous>)
    at /Users/[...]/node_modules/eslint-plugin-react/lib/rules/prop-types.js:152:26
    at Array.forEach (<anonymous>)
    at isDeclaredInDestructuredParam (/Users/[...]/node_modules/eslint-plugin-react/lib/rules/prop-types.js:147:14)
    at isDeclaredInComponent (/Users/[...]/node_modules/eslint-plugin-react/lib/rules/prop-types.js:189:18)
    at /Users/[...]/node_modules/eslint-plugin-react/lib/rules/prop-types.js:204:13
    at Array.filter (<anonymous>)
    at reportUndeclaredPropTypes (/Users/[...]/node_modules/eslint-plugin-react/lib/rules/prop-types.js:201:51)
    at /Users/[...]/node_modules/eslint-plugin-react/lib/rules/prop-types.js:226:11
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ljharb** [comment] 2020-09-30 18:34
Duplicate of #2806. Duplicate of #2804.

Will be fixed in the next release.

**Closed by ljharb** 2020-09-30 18:34 UTC
