### ISSUE TITLE
jsx-no-undef does not support dynamic JSX tags

### ISSUE THREAD

**Issue by darrenscerri** [yannickcr/eslint-plugin-react#484] opened 2016-03-04 15:09 UTC
```js
class Component extends React.Component {
  render() {
    return (
      <this.props.tag>Test</this.props.tag>
    );
  }
}
```

Eslint is complaining:

`react/jsx-no-undef 'undefined' is not defined`

**Comment by ljharb** [comment] 2016-03-04 16:59
@darrenscerri Duplicate of #481 and #469. Fixed in ebab180 but not published yet.

**Comment by yannickcr** [comment] 2016-03-06 21:48
Fixed in `v4.2.0`

**Closed by yannickcr** 2016-03-06 21:48 UTC

**Comment by darrenscerri** [comment] 2016-03-07 10:15
Issue still persists in `v4.2.0` when using `this`.
