### ISSUE TITLE
Declaring `propTypes` on a non-component object throws

### ISSUE THREAD

**Issue by alexlrobertson** [yannickcr/eslint-plugin-react#1934] opened 2018-08-14 14:58 UTC
`Imported.js`
```jsx
const PropTypes = require('prop-types');

const Imported = () => {
  return null;
};

Imported.propTypes = {};

module.exports = Imported.
```

`Components.js`
```jsx
const Imported = require('./Imported');

const Components = {
  AComponent: (props) => <Imported {...props} />
};

Components.propTypes = Imported.propTypes;

module.exports = Components;
```

```
Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at markPropTypesAsDeclared (/Users/arobert3/Sites/eslint-bug/node_modules/eslint-plugin-react/lib/util/propTypes.js:475:51)
    at Object.MemberExpression (/Users/arobert3/Sites/eslint-bug/node_modules/eslint-plugin-react/lib/util/propTypes.js:644:9)
    at updatedRuleInstructions.(anonymous function) (/Users/arobert3/Sites/eslint-bug/node_modules/eslint-plugin-react/lib/util/Components.js:706:43)
    at listeners.(anonymous function).forEach.listener (/Users/arobert3/Sites/eslint-bug/node_modules/eslint/lib/util/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/arobert3/Sites/eslint-bug/node_modules/eslint/lib/util/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/arobert3/Sites/eslint-bug/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/Users/arobert3/Sites/eslint-bug/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (/Users/arobert3/Sites/eslint-bug/node_modules/eslint/lib/util/node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (/Users/arobert3/Sites/eslint-bug/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:632:23)
```

**Comment by ljharb** [comment] 2018-08-14 15:01
Fixed by #1932, duplicate of #1928.

**Closed by ljharb** 2018-08-14 15:01 UTC
