### ISSUE TITLE
Recent version 7.29.0 raises 'Missing "key" prop for element in array  react/jsx-key' unnecessarily; breaks build

### ISSUE THREAD

**Issue by martha-anne** [yannickcr/eslint-plugin-react#3217] opened 2022-02-25 11:45 UTC
When using version 7.29.0 in my webapp and running a build I am seeing thousands of 'Missing "key" prop for element in array  react/jsx-key' errors which seem to be raised for every file, against lines which do not involve arrays at all. It appears to be raised any time an element contains any other element.

Versioning down to 7.28.0 fixes the issue.

Example

```
src/ui/components/resourceVideo/ResourceVideo.tsx
  Line 17:7:  Missing "key" prop for element in array  react/jsx-key
  Line 17:7:  Missing "key" prop for element in array  react/jsx-key
  Line 18:7:  Missing "key" prop for element in array  react/jsx-key
  Line 18:7:  Missing "key" prop for element in array  react/jsx-key
```

ResourceVideo.tsx:
```
import React, { FC, useRef, useState } from 'react';

import './ResourceVideo.sass';
import VimeoVideoPlayInModal from '../vimeoVideoPlayInModal/VimeoVideoPlayInModal';

type Props = {
  videoUrl: string;
  videoTitle: string;
};
const ResourceVideo: FC<Props> = ({
  videoUrl,
  videoTitle,
}: Props): JSX.Element => {
  return (
    <div className="resource-video">
      <VimeoVideoPlayInModal videoUrl={videoUrl} />
      <h3>{videoTitle}</h3>
    </div>
  );
};

export default ResourceVideo;
```

**Comment by Fox32** [comment] 2022-02-25 11:46
See #3215

**Comment by yoyo837** [comment] 2022-02-25 11:52
Duplicate of #3215

**Comment by ljharb** [comment] 2022-02-25 18:12
Duplicate of #3215.

**Closed by ljharb** 2022-02-25 18:12 UTC

**Comment by ljharb** [comment] 2022-02-25 19:01
v7.29.1 is released.
