### ISSUE TITLE
TypeError: Cannot read property 'callee' of null 7.20.5

### ISSUE THREAD

**Issue by Romanior** [yannickcr/eslint-plugin-react#2743] opened 2020-08-05 10:50 UTC
At version 7.20.5

this code
```
export const setMainBodyClass = className => {
  if (className && className.trim().indexOf(' ') >= 0) {
    throw Error('You can only set one main body class');
  }
  const { classList } = document.body;
  if (
    className &&
    currentBodyClass === className &&
    classList.contains(className)
  ) {
    return;
  }
  if (currentBodyClass && classList.contains(currentBodyClass)) {
    classList.remove(currentBodyClass);
    currentBodyClass = null;
  }
  if (className && !classList.contains(className)) {
    classList.add(className);
    currentBodyClass = className;
  }
};
```
line with single `return` raises:
TypeError: Cannot read property 'callee' of null
```
Occurred while linting
    at Object.isDestructuredFromPragmaImport (.../node_modules/eslint-plugin-react/lib/util/Components.js:348:33)
    at Object.isCreateElement (.../node_modules/eslint-plugin-react/lib/util/Components.js:393:16)
    at Object.isReturningJSX (.../node_modules/eslint-plugin-react/lib/util/Components.js:467:47)
    at Object.ReturnStatement (.../node_modules/eslint-plugin-react/lib/util/Components.js:942:18)
    at updatedRuleInstructions.(anonymous function) (.../node_modules/eslint-plugin-react/lib/util/Components.js:970:43)
    at listeners.(anonymous function).forEach.listener (.../node_modules/eslint/lib/linter/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (.../node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (.../node_modules/eslint/lib/linter/node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (.../node_modules/eslint/lib/linter/node-event-generator.js:283:22)
````

**Comment by ljharb** [comment] 2020-08-06 05:48
Duplicate of #2733.

**Closed by ljharb** 2020-08-06 05:48 UTC
