### ISSUE TITLE
Forbid prop names

### ISSUE THREAD

**Issue by palnes** [yannickcr/eslint-plugin-react#468] opened 2016-02-25 12:22 UTC
I would love a way to forbid certain prop-names, in similar fashion to https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/forbid-prop-types.md

In my case I want to make sure no one adds inline styles.

Bad: 
```
<MyComponent style={{color:#b00b00}} />
```

Good:
```
<MyComponent className="properCSS" />
```

**Comment by lencioni** [comment] 2016-07-24 20:48
This is basically a duplicate of #314, which I've implemented in #703.

**Closed** 2016-07-24 21:45 UTC
