### ISSUE TITLE
Rule Proposal: prefer-pure-render-mixin

### ISSUE THREAD

**Issue by naddeoa** [yannickcr/eslint-plugin-react#310] opened 2015-11-16 01:15 UTC
I didn't see anything like this already, but I think it would be very useful. I'll write the rule doc here as an explanation.

## Rule Details
The following patterns are considered warnings

```javascript
var Hello = React.createClass({
  render: function() {
    return <div>Hello {this.props.name}</div>;
  }
});
```

The following patterns are not considered warnings
```javascript
import PureRenderMixin from 'react-addons-pure-render-mixin';
var Hello = React.createClass({
  mixins : [PureRenderMixin],
  render: function() {
    return <div>Hello {this.props.name}</div>;
  }
});
```

```javascript
// Backwards compatible with pre 0.14 React versions
var PureRenderMixin = require('react').addons.PureRenderMixin;
var Hello = React.createClass({
  mixins : [PureRenderMixin],
  render: function() {
    return <div>Hello {this.props.name}</div>;
  }
});
```

It is probably possible to do something more intelligent than just checking for the presence of the mixin, but it would guarantee that anyone checking in components without the mixin would at least break the build.

**Comment by Daniel15** [comment] 2015-11-16 20:01
Duplicate of #240

**Comment by yannickcr** [comment] 2015-11-16 21:07
Duplicate, as said by @Daniel15 :)

**Closed by yannickcr** 2015-11-16 21:07 UTC
