### ISSUE TITLE
jsx-no-undef undefined bug with deep object access

### ISSUE THREAD

**Issue by Kerumen** [yannickcr/eslint-plugin-react#481] opened 2016-03-03 12:45 UTC
Following #172, with this:
```javascript
import List from './List';

const label = <List.Item.Label>Hello</List.Item.Label>
```
I have the error `'undefined' is not defined`.

**Comment by yannickcr** [comment] 2016-03-03 22:16
Duplicate of #469, it was fixed in https://github.com/yannickcr/eslint-plugin-react/commit/ebab1800536c4abf0491c7afa73d6652ee133082 but not published yet (it should be published during the week-end)

**Closed by yannickcr** 2016-03-03 22:16 UTC
