### ISSUE TITLE
New rule: Use ternaries rather than && in JSX

### ISSUE THREAD

**Issue by MichaelDeBoey** [yannickcr/eslint-plugin-react#3153] opened 2021-12-06 16:29 UTC
Inspired by @kentcdodds' [article](https://kentcdodds.com/blog/use-ternaries-rather-than-and-and-in-jsx), It would be awesome to have an ESLint rule that supports this.

**Comment by ljharb** [comment] 2021-12-06 19:42
Now that `??` exists, there's not really a need to use ternaries here.

I think this is a duplicate of #2073.

**Closed by ljharb** 2021-12-06 19:42 UTC

**Comment by MichaelDeBoey** [comment] 2022-06-04 09:47
This got fixed by #3203

Huge thanks @Belco90! 🤩
