### ISSUE TITLE
Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by syakuis** [yannickcr/eslint-plugin-react#1586] opened 2017-12-06 05:43 UTC
`type object undefined` checking required ...

```
"eslint": "^4.12.1",
"eslint-config-airbnb": "^16.1.0",
"eslint-plugin-import": "^2.8.0",
"eslint-plugin-jsx-a11y": "^6.0.2",
"eslint-plugin-react": "^7.5.1",
```

$ eslint ~/path/

error log

```
Cannot read property 'type' of undefined
TypeError: Cannot read property 'type' of undefined
    at checkValidPropObject (/Users/syaku/develop/IntelliJ/portal/frontend/node_modules/eslint-plugin-react/lib/rules/no-typos.js:76:15)
    at checkValidProp (/Users/syaku/develop/IntelliJ/portal/frontend/node_modules/eslint-plugin-react/lib/rules/no-typos.js:65:11)
    at node.properties.forEach.prop (/Users/syaku/develop/IntelliJ/portal/frontend/node_modules/eslint-plugin-react/lib/rules/no-typos.js:77:41)
    at Array.forEach (native)
    at checkValidPropObject (/Users/syaku/develop/IntelliJ/portal/frontend/node_modules/eslint-plugin-react/lib/rules/no-typos.js:77:25)
    at reportErrorIfClassPropertyCasingTypo (/Users/syaku/develop/IntelliJ/portal/frontend/node_modules/eslint-plugin-react/lib/rules/no-typos.js:85:9)
    at MemberExpression (/Users/syaku/develop/IntelliJ/portal/frontend/node_modules/eslint-plugin-react/lib/rules/no-typos.js:135:11)
    at listeners.(anonymous function).forEach.listener (/Users/syaku/develop/IntelliJ/portal/frontend/node_modules/eslint/lib/util/safe-emitter.js:47:58)
    at Array.forEach (native)
    at Object.emit (/Users/syaku/develop/IntelliJ/portal/frontend/node_modules/eslint/lib/util/safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (/Users/syaku/develop/IntelliJ/portal/frontend/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/Users/syaku/develop/IntelliJ/portal/frontend/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (/Users/syaku/develop/IntelliJ/portal/frontend/node_modules/eslint/lib/util/node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (/Users/syaku/develop/IntelliJ/portal/frontend/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:23)
    at Traverser.enter (/Users/syaku/develop/IntelliJ/portal/frontend/node_modules/eslint/lib/linter.js:956:32)
    at Traverser.__execute (/Users/syaku/develop/IntelliJ/portal/frontend/node_modules/estraverse/estraverse.js:397:31)
```

my code cause

```
Link.propTypes = {
  url: PropTypes.string,
  urlMode: PropTypes.string,
  children: PropTypes.node,
  style: PropTypes.shape(),  // <--- here cause 
  options: PropTypes.shape({
    name: PropTypes.string,
    width: PropTypes.number,
    height: PropTypes.number,
  }),
};
```

```
style: PropTypes.shape({}) // <---- resolved
```

**Comment by jseminck** [comment] 2017-12-06 05:49
What does it mean when you define a prop as `PropTypes.shape()`. Does it even make sense to have this?

**Comment by syakuis** [comment] 2017-12-06 05:56
That code is my fault. However, I could not figure out where the error occurred, so I had trouble solving it.

**Comment by ljharb** [comment] 2017-12-06 06:47
This is a duplicate of #1471.

**Closed by ljharb** 2017-12-06 06:47 UTC
