### ISSUE TITLE
jsx-closing-bracket-location think of 'space' and 'tab' as the same thing

### ISSUE THREAD

**Issue by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [yannickcr/eslint-plugin-react#756] opened 2016-08-09 02:16 UTC
my config

```
"react/jsx-indent": ["warn", "tab"],
"react/jsx-indent-props": ["warn", "tab"],
"react/jsx-closing-bracket-location": ["warn", {
  "nonEmpty": "tag-aligned"
}],
```

my code

``` jsx
        <div
            className={ styles.header_title }
  >
            { props.title }
        </div>
```

opening tag has 2 tabs, closing bracket has 2 spaces but this case doesn't have any warning or error.

**Comment by iTob191** [comment] 2016-10-02 16:18
Using `--fix` also results in an output like above.

**Comment by Kyle-Mendes** [comment] 2017-01-24 05:57
I'm still seeing this issue.  It's causing a lot of problems on a big team, some people aren't used to working with tabs and the only way to catch the issue is via code review.

**Comment by Moong0122** [comment] 2020-08-02 13:18
May I try to solve this bug?

**Comment by ljharb** [comment] 2020-08-02 20:12
@Moong0122 yes, anything with the "help wanted" label that doesn't already have a PR, you can just make a PR for it :-)

**Comment by Moong0122** [comment] 2020-08-30 08:25
I understand that if the rule `react/jsx-indent": ["warn", "tab"]` is used, an error occurs when the tab is not used.
But there's no error in the code here.
Where do you think the problem occurred between `react/jsx-indent` and `jsx-closing-bracket-location`?

**Comment by ljharb** [comment] 2020-08-30 18:33
I would expect jsx-closing-bracket-location to be the thing that warns, because jsx-indent would determine where `<div` is, and then closing-bracket-location would use *that* to determine where `>` should be.

**Closed** 2020-09-16 06:31 UTC
Labels: bug, help wanted
