### ISSUE TITLE
no-unused-prop-types rule not detect nest object

### ISSUE THREAD

**Issue by mydearxym** [yannickcr/eslint-plugin-react#847] opened 2016-09-17 00:12 UTC
this is working : 

```js
class Foo extends React.Component {
    render: function () {
        return <div>{this.props.bar.baz}</div>
    }
}
Foo.propTypes = {
    bar: React.PropTypes.shape({  
        baz: React.PropTypes.string      // ok
    })
};
```

but this seems not work:
```js
class Foo extends React.Component {
    const bar = this.props.bar;

    render: function () {
        return <div>{bar.baz}</div>
    }
}
Foo.propTypes = {
    bar: React.PropTypes.shape({  
        baz: React.PropTypes.string      // not ok, Prop defined but not used
    })
};
```

**Comment by mydearxym** [comment] 2016-09-17 00:29
it seems to be the `no-unused-prop-types"` issue  #837

**Comment by EvNaverniouk** [comment] 2016-09-30 22:51
Duplicate of #871. 

The `no-unused-prop-types` rule does not support `shape` props at the moment as such detection is very difficult. If you use shape props, I recommend setting the `skipShapeProps` option to `true` on the rule.

**Closed** 2016-10-01 18:16 UTC
Labels: bug

**Comment by alenia** [comment] 2017-04-15 01:11
Is this still unsupported?
