### ISSUE TITLE
destructuring-assignment in class properties

### ISSUE THREAD

**Issue by alexandernanberg** [yannickcr/eslint-plugin-react#1875] opened 2018-07-04 07:05 UTC
First I'd like to just say that I like the new `destructuring-assignment` rule because I think it enforces a lot more clarity and explicitness. However I'm having problems with it throwing errors inside of class properties. 

```javascript
class MyComponent extends React.Component {
  state = {
    value: this.props.defaultValue,
  };

  ...
}
```
IMO this should be an exception and be totally valid or at least have the option to exclude it just from this use-case. I know that I could move it inside a `constructor` and destructure it there but I'd rather not do that.

**Comment by ljharb** [comment] 2018-07-04 07:10
Duplicate of #1800.

An option would be great.

**Comment by MichielLeyman** [comment] 2018-07-18 18:59
This isn't a duplicate, #1800 is about it erroring in files that have nothing to do with react. I have the same issue, complains about destructuring in class properties

**Comment by ljharb** [comment] 2018-07-18 20:58
Fair point; I'll reopen.

**Closed** 2018-08-05 23:16 UTC
Labels: enhancement, help wanted
