### ISSUE TITLE
[jsx-pascal-case] label variable fail

### ISSUE THREAD

**Issue by yordis** [yannickcr/eslint-plugin-react#343] opened 2015-12-01 17:51 UTC
The label tag is failing on this rule

Imported JSX component label must be in PascalCase  `react/jsx-pascal-case`

**Comment by yannickcr** [comment] 2015-12-01 20:37
Can you give me a code sample that trigger that invalid lint errors ?

**Comment by playpauseandstop** [comment] 2015-12-02 19:32
I ran into same problem today with this code,

```js
  render() {
    const {label} = this.props;
    return <label className="...">{label}</label>;
  }
```

From my perspective it happens, cause ESLint seeing defined `label` var in current scope and considers warning for pascal-case in `<label>` JSX tag.

ps. I fixed the error with `const {label: labelText} = this.props;`

**Comment by yordis** [comment] 2015-12-02 19:42
@yannickcr yep the same here
`<label htmlFor={name}>{label}</label>`

**Comment by yannickcr** [comment] 2015-12-05 19:24
Seems to be a duplicate of #329

**Closed by yannickcr** 2015-12-05 19:24 UTC
