### ISSUE TITLE
Destructured use of property is not recognized by no-unused-prop-types

### ISSUE THREAD

**Issue by kumar303** [yannickcr/eslint-plugin-react#816] opened 2016-09-09 20:11 UTC
Given a React component like:

``` javascript
export default class Thing extends React.Component {
  static propTypes = {
    i18n: PropTypes.shape({
      gettext: PropTypes.func,
    }).isRequired,
  }

  render() {
    const { i18n } = this.props;

    return (
      <div>
        <span>{i18n.gettext('Some Text')}</span>
      </div>
    );
  }
}
```

And the following eslint rule:

```
"react/no-unused-prop-types": "error"
```

I see the following error:

```
/Users/kumar/tmp/eslint-scratch/index.js
  6:16  error  'i18n.gettext' PropType is defined but prop is never used  react/no-unused-prop-types
```

This is incorrect because the `i18n` property is destructured into a new constant and then the `gettext()` function is called. If I edit the code so that it doesn't use destructuring then the error goes away, revealing the bug.

Here is a small app that reproduces it: [eslint-scratch.zip](https://github.com/yannickcr/eslint-plugin-react/files/464733/eslint-scratch.zip). Run:

```
npm install
npm run eslint
```

This is similar to https://github.com/yannickcr/eslint-plugin-react/issues/782 but they seem different.

**Comment by yury-dymov** [comment] 2016-09-12 17:55
I am facing very similar case but a bit different:

```
const propTypes = {
  clientVersion:  PropTypes.string,
};

const defaultProps = {
  clientVersion: null,
};

class App extends Component {
  constructor(props) {
    super(props);

    this.checkClientVersion = this.checkClientVersion.bind(this);
  }

  checkClientVersion(props = this.props) {     // <-- might puzzle parser but still a valid use-case
    const { clientVersion } = props;                   // <-- used!
   <...>
  }

  render() {
    <...>
}

App.propTypes     = propTypes;
App.defaultProps  = defaultProps;

export default App;
```

**Comment by ljharb** [comment] 2016-09-12 18:25
@yury-dymov in your case, it's only used if they don't pass in a `props` arg - can I ask what the use case for that is? It seems very un-React.

**Comment by yury-dymov** [comment] 2016-09-13 02:13
@ljharb, well, to me it looks very common
```
  componentDidMount() {
    this.checkClientVersion();
  }

  componentWillReceiveProps(nextProps) {
    <...>
    this.checkClientVersion(nextProps);
  }


  checkClientVersion(props = this.props) {
    const { clientVersion } = props;
    <...>
  }

```

So, basically it is helper method, which is called to do whatever, when props are provided/updated. Normally it is called with no parameters but for `componentWillReceiveProps()` I want to pass nextProps instead of current.

**Comment by ljharb** [comment] 2016-09-13 05:58
If it's a helper method, it shouldn't be an instance method - and then this plugin won't warn on it. Instance methods should use `this` in all code paths, otherwise they shouldn't be instance methods.

**Comment by tristanbbq** [comment] 2016-09-15 19:02
Could this be related: https://github.com/yannickcr/eslint-plugin-react/pull/611 ?

**Comment by EvNaverniouk** [comment] 2016-09-15 19:06
I've been thinking about the best way to handle this. The only thing I can think of is to build some common conventions into the rule. ie. Any function that uses the following patterns `this.props.something` or `props.something`, or `nextProps.something` or `prevProps.something` would count towards being considered used.

It will prevent false positive warnings, but would also not catch certain cases where the object isn't actually the component props.

Thoughts?

**Comment by nkt** [comment] 2016-10-18 10:12
This is not linting rule, it's static analysis rule. Static analyzer should be able to resolve variables instead just checking them by some "mask".
I guess this project needs magic function `resolveVariables`, this function can solve many issues:
```js
// user code
const { settings: { foo } } = this.props;

// plugin
resolve('foo') -> this.props.settings.foo
```
```js
// user code
const { users } = this.props;
users.map(({ id }) => ...);

// plugin
resolve('id') -> this.props.users[].id
```

**Comment by Andreyco** [comment] 2016-11-07 08:46
I got false positive connected to destruction assignment.

Code preview
```jsx
export default class NavigationButton extends React.Component {
  static propTypes = {
    route: PropTypes.shape({
      getBarTintColor: PropTypes.func.isRequired,
    }).isRequired,
  };

  renderTitle() {
    const { route } = this.props;
    return <Title tintColor={route.getBarTintColor()}>TITLE</Title>;
  }
}
```

I get this false report, despite `getBarTintColor` is clearly used.
```
'route.getBarTintColor' PropType is defined but prop is never used
```

**Comment by juliacochran** [comment] 2016-11-08 00:15
I am seeing this as well when using `PropTypes.arrayOf(PropTypes.shape({...})` and then mapping the prop in `render`

**Comment by numbergames** [comment] 2017-03-06 06:58
Sorry to pile on, but I believe this is one more unique example of inaccurate triggering of the when props are destructured and reassigned.

```
import React from 'react';

const Component = ({ children: aNode }) => (
  <div>
    {aNode}
  </div>
);

Component.defaultProps = {
  aNode: null,
};

Component.propTypes = {
  aNode: React.PropTypes.node,
};
```
Throws two errors: 
`'Children' is missing in props validation at ...`
`'aNode' PropType is defined but never used at ...`

**Comment by Andreyco** [comment] 2017-03-06 09:04
@numbergames
Warnings in this case are valid.  
```js
const Component = ({ children: aNode }) => (
   // ...
);

// is equivalent of this

const Component = (props) => {
  const { children: aNode } = props;
  // ...
}
```

Thus, all prop validation does apply to original prop names - not aliased. Same apply to `defaultProps`

Correct usage would be:
```js
import React from 'react';

const Component = ({ children: aNode }) => (
  <div>
    {aNode}
  </div>
);

Component.defaultProps = {
  children: null,
};

Component.propTypes = {
  children: React.PropTypes.node,
};
```

**Comment by mike-robertson** [comment] 2017-03-18 13:49
Here's an even weirder bug that may be related to all this. I'm using flow and this keeps coming up:

```js

  onInputChange({ target: { value: inputValue } }: { target: { value: string } }) {
  //                                                                                        ^^^^
  // target.value PropType is defined but prop is never used (react/no-unused-prop-types)
    this.setState({
      inputValue,
      inputWidth: Select.defaultInputWidth + (7 * inputValue.length),
    });
  }
```

I have no idea why this would think there are props here. It's inside a class component; it's not even related to props, I'm just destructuring an event object.

**Comment by ljharb** [comment] 2017-03-18 19:49
@mike-robertson yours is likely a bug specific to Flow; can you file a separate issue for that?

**Comment by anshulsahni** [comment] 2017-04-05 10:12
```
const bolusInsulin = find(props.insulins, { value: getIdFromUrl(props.bolusInsulin) }) || {};
```

In PropTypes
```
GlucoseSettings.propTypes = {
  insulinRegimen: PropTypes.string,
  bolusInsulin: PropTypes.string,
  insulins: PropTypes.array,
};
```
still the error reads

```
72:17  error  'bolusInsulin' PropType is defined but prop is never used  react/no-unused-prop-types
73:13  error  'insulins' PropType is defined but prop is never used      react/no-unused-prop-types
```

**Comment by ljharb** [comment] 2017-04-05 17:25
@anshulsahni Can you share more code? Where does that find appear?

**Comment by anshulsahni** [comment] 2017-04-06 13:13
@ljharb 

this is the full component code, certain pieces of code are hidden

```
import React, { PropTypes } from 'react';

import pick from 'lodash/pick';
import find from 'lodash/find';

import { getIdFromUrl } from ...
import CorrectionalInsulin from ...
import InsulinRegimen from ...
import CarbCounting from ...
import LimitsEdit from ...

import '../../styles/index.scss';

const correctionalInsulinProps = [
...
];

const limitsEditProps = [
...
];

const insulinRegimenProps = [
....
];

const GlucoseSettings = (props) => {
  const renderCorrectional = () => (
    <CorrectionalInsulin
      {...pick(props, correctionalInsulinProps)}
    />
  );

  const renderCarbCounting = () => {
    const bolusInsulin = find(props.insulins, { value: getIdFromUrl(props.bolusInsulin) }) || {};
    return (
      <CarbCounting
        bolusInsulin={bolusInsulin.name}
      />
    );
  };

  return (
    <div className="glucose-settings">
      <LimitsEdit
        {...pick(props, limitsEditProps)}
      />
      <InsulinRegimen
        {...pick(props, insulinRegimenProps)}
      />
      {props.insulinRegimen.includes('carb_counting') ? renderCarbCounting() : null}
      {props.insulinRegimen.includes('mixed') ? null : renderCorrectional()}

    </div>
  );
};

GlucoseSettings.propTypes = {
  insulinRegimen: PropTypes.string,
  bolusInsulin: PropTypes.string,
  insulins: PropTypes.array,
};

GlucoseSettings.defaultProps = {
  insulinRegimen: '',
  insulins: [],
  bolusInsulin: '',
};

export default GlucoseSettings;
```

**Comment by mqklin** [comment] 2017-04-17 13:41
I have a warning with flow too. My code:

```
type Props = {
  obj: {num: number},
};
...

props: Props;
...
render() {
  const {obj: {num}} = this.props; // < obj.num PropType is defined but prop is never used (react/no-unused-prop-types)
}
```

**Comment by robguy21** [comment] 2017-04-26 07:54
Just adding my snippet here...

```js
type HeaderPropTypes = {
  actions: { unAuth: () => any }, // error  'actions.unAuth' PropType is defined but prop is never used  react/no-unused-prop-types
};

const Header = ({ actions }: HeaderPropTypes): React$Element<*> => (
  <div>
      <button
        className="btn--secondary"
        onClick={
          function logout(): boolean {
            flushAuth(actions.unAuth);
            return true;
          }
        }
      >
        Log Out
      </button>
  </div>
);

const mapDispatchToProps = (dispatch: () => any): {} => ({
  actions: bindActionCreators(Actions, dispatch),
});

```

**Comment by anshulsahni** [comment] 2017-04-26 09:16
@ljharb any update on this ?

**Comment by ljharb** [comment] 2017-04-26 16:56
Nope, it's marked "help wanted"

**Comment by mrm007** [comment] 2017-06-21 03:40
@ljharb How can we help? I can take a stab at it if you point me in the right direction.

**Comment by ljharb** [comment] 2017-06-21 04:20
@mrm007 i'd start by adding the relevant test cases to `no-unused-prop-types`, and then try to make them pass :-D

**Comment by mrm007** [comment] 2017-06-21 04:24
It's this kind of snark that I came here for. Thanks!

**Comment by ljharb** [comment] 2017-06-21 04:27
@mrm007 i realize the tone is snarky, but i'm quite serious - that's the best way to go about fixing it. I'm not actually sure beyond that what AST parsing changes you might need to make to fix the issue; otherwise i'd have made a PR myself :-)

**Comment by BertelBB** [comment] 2017-07-11 13:19
Another one for you
```
componentDidMount = () => this.checkForAccount(this.props)

componentWillReceiveProps = nProps => this.checkForAccount(nProps)

checkForAccount({ account, ... }) {...}

...

AccountContainer.propTypes = {
	account: PropTypes.shape(PropTypes.shape({
		...
	}).isRequired).isRequired,
	...
}
```

```
[eslint] 'account' PropType is defined but prop is never used (react/no-unused-prop-types)
```

**Comment by ljharb** [comment] 2017-07-11 18:29
@BertelBB I'm confused - why are your lifecycle methods instance properties instead of prototype methods? That seems wildly incorrect.

Regardless, passing around the entire `props` object is always going to make linting it untenable - destructure it the first time you interact with it, and pass those items around, and everything should work fine.

**Comment by BertelBB** [comment] 2017-07-11 23:10
@ljharb I'm also confused. I'm not sure what you mean.

I'm pretty sure my lifecycle methods are not instance properties.
```
import React, { Component } from 'react'
...
export default class AccountContainer extends Component {
	constructor(props) {
		super(props)
		this.state = {
			someStatePassableDownChain = '' // <- Instance property ?
		}
		...
		this.checkForAccount = this.checkForAccount.bind(this) // <- Also instance property ?
	}
	componentDidMount = () => this.checkForAccount(this.props)

	componentWillReceiveProps = nProps => this.checkForAccount(nProps)

	checkForAccount({ account, ... }) {...}

	...
}

AccountContainer.propTypes = {
	account: PropTypes.shape(PropTypes.shape({
		...
	}).isRequired).isRequired,
	...
}
```

The reason for passing the entire ```props``` object to ```checkForAccount```, is because I am using more than one property in that function. Depending on if a specific property has changed, I need to ```do stuff```. I would like to pass the entire object and destructure it in checkForAccount, rather than pass each property individually as a parameter in each lifecycle method. Is there something wrong with that?

**Comment by ljharb** [comment] 2017-07-12 08:06
Because you're using class property syntax (`componentDidMount = anArrowFunction`) they're instance properties. You need to be using method syntax:
```js
export default class AccountContainer extends Component {
	constructor(props) {
		…
	}
	componentDidMount() {
          this.checkForAccount(this.props);
        }

	componentWillReceiveProps(nProps) {
          this.checkForAccount(nProps);
        }

	checkForAccount({ account, ... }) {
          …
        }

	...
}
```

**Comment by BertelBB** [comment] 2017-07-12 08:11
@ljharb Ok I had no idea there were more than syntax differences.. thanks so much!

**Comment by DianaSuvorova** [comment] 2017-07-21 22:21
@ljharb  I have created a [PR](https://github.com/yannickcr/eslint-plugin-react/pull/1312) with (what I think) all of the valid use cases discussed in this thread.
Most of them are fixed already. I found only one reported by @robguy21, that needs to be investigated (I commented it out and will look into it).  Please let me know if missed any other valid cases from this issue. Thanks!

**Comment by DianaSuvorova** [comment] 2017-07-22 21:21
@ljharb, here is the summary of this thread. 

There are 3 separate types of errors were reported/discussed here:
 - **PropTypes.shape** officially this rule doesn't support it . By default the options for this rule  is [{skipShapeProps: true}]. There are quite a few  people reported test cases that uses `PropTypes.shape` (including the very first one) without any modification their test cases passes as I demonstrated in a PR. As soon as one sets `[{skipShapeProps: false}]` these cases are going to fail. 

- **Destructuring assignment**. This works just fine. The problem is that destructuring assignment is often times  used with shape type. Thus it is really easy to assume that it is a problem.

- **Flow Components**. This is the one I though needs to be checked but then I realized it is a flow. So I am not really sure what's this library strategy for supporting flow. For this rule I would propose to skip flow components (can be a config option) unless there is a better ideas. This can be done as a separate ticket/PR.

With that I think we can actually close this ticket. I will update my pr to format the tests correctly. But there is going to be no code change. 

LMK your thoughts.

**Comment by ljharb** [comment] 2017-07-22 22:34
Thanks for that summary - I'd say the flow issues should be supported, ideally, by a separate PR is fine; and the issues with shape props are known.

**Closed** 2017-07-23 04:52 UTC
Labels: bug, help wanted

**Comment by leonardovillela** [comment] 2018-12-11 19:37
The flow case is fixed? Exists other issue for it?

**Comment by djbobbydrake** [comment] 2019-10-02 15:39
> * **Destructuring assignment**. This works just fine. The problem is that destructuring assignment is often times  used with shape type. Thus it is really easy to assume that it is a problem.

I believe there's been a regression in 7.14.3.  When I destructure a proptype while in 7.14.3, it errors out for me.  When I pin the version to 7.14.2, no errors.

**Comment by ljharb** [comment] 2019-10-02 16:14
@djbobbydrake what about v7.15.1?

**Comment by djbobbydrake** [comment] 2019-10-02 16:35
@ljharb errors out for me in 7.15.1 also

**Comment by ljharb** [comment] 2019-10-02 16:56
Thanks for confirming; can you please file a new issue? The sooner we can get a test case the sooner we can fix it :-)
