### ISSUE TITLE
no-typos rule doesn't support `isRequired` when destructuring

### ISSUE THREAD

**Issue by ranneyd** [yannickcr/eslint-plugin-react#1488] opened 2017-10-18 17:14 UTC
I have the following:

```
const { func } = PropTypes;
Component.propTypes = {
   prop: func.isRequired,
}
```

The plugin is marking `isRequired` as invalid, saying
> Typo in declared proptype: isRequired (react/no-typos)

Perhaps there's some regular expression thing that's checking after the first `.`, aka assuming it begins with `PropTypes`?

**Comment by ljharb** [comment] 2017-10-19 04:08
Duplicate of #1389.

**Closed by ljharb** 2017-10-19 04:08 UTC
