### ISSUE TITLE
jsx-no-target-blank false positive

### ISSUE THREAD

**Issue by jahirfiquitiva** [yannickcr/eslint-plugin-react#2549] opened 2020-01-22 20:21 UTC
I have enabled `react/jsx-curly-brace-presence` but now the `react/jsx-no-target-blank` rules is considering the following snippet as error:

```javascript
<a className={'App-link'}
         href={'https://reactjs.org'}
         target={'_blank'}
         rel={'noopener noreferrer'}>Learn React</a>
```

What can I do to fix it so it doesn't consider it an error?

**Comment by ljharb** [comment] 2020-01-23 21:52
Duplicate of #2508; will be solved by #2544.

**Closed by ljharb** 2020-01-23 21:52 UTC
