### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by hkolsen** [yannickcr/eslint-plugin-react#2257] opened 2019-05-02 16:23 UTC
Using Eslint v5.16.0 and `eslint-plugin-react` v7.12.4

```
TypeError: Cannot read property 'length' of undefined
    at reportInvalidEntity (/Users/heidiolsen/Documents/my-project/node_modules/eslint-plugin-react/lib/rules/no-unescaped-entities.js:51:27)
    at Literal, JSXText (/Users/heidiolsen/Documents/my-project/node_modules/eslint-plugin-react/lib/rules/no-unescaped-entities.js:77:11)
    at listeners.(anonymous function).forEach.listener (/Users/heidiolsen/Documents/my-project/node_modules/eslint/lib/util/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/heidiolsen/Documents/my-project/node_modules/eslint/lib/util/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/heidiolsen/Documents/my-project/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/Users/heidiolsen/Documents/my-project/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (/Users/heidiolsen/Documents/my-project/node_modules/eslint/lib/util/node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (/Users/heidiolsen/Documents/my-project/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:632:23)
    at nodeQueue.forEach.traversalInfo (/Users/heidiolsen/Documents/my-project/node_modules/eslint/lib/linter.js:752:32)
```

Seemed to occur when there was a stray `’` inside JSX.

**Comment by ljharb** [comment] 2019-05-02 16:58
@hkolsen thanks! any chance you have an exact code sample that can repro the error?

**Comment by hkolsen** [comment] 2019-05-02 17:06
Hi @ljharb, thank you for responding so quickly. The best way to replicate the issue is by adding a block of text with a `’` smart apostrophe (otherwise called curly/sloped) instead of a straight apostrophe `'`. However if you are using `<FormattedMessage>`, eslint does not have the same issue.

Let me know if you need any additional info!

**Comment by ljharb** [comment] 2019-05-02 19:13
hmm, I'm unable to reproduce it. Can you provide your eslint and plugin versions, your eslint config, and ideally the component code in question?

**Comment by JounQin** [comment] 2019-09-29 14:29
+1 for this when using with `@typescript-eslint`

**Comment by ljharb** [comment] 2019-09-29 15:37
@JounQin do you know what code this errors on?

**Comment by ljharb** [comment] 2022-02-18 23:10
Closing pending a reproducible test case.

**Closed by ljharb** 2022-02-18 23:10 UTC
Labels: bug, help wanted, question, typescript
