### ISSUE TITLE
Move getStandardName logic from no-unknown-property into separate package

### ISSUE THREAD

**Issue by davidtheclark** [yannickcr/eslint-plugin-react#1258] opened 2017-06-14 01:43 UTC
The [`getStandardName` function](https://github.com/yannickcr/eslint-plugin-react/blob/master/lib/rules/no-unknown-property.js#L152-L170), which converts HTML attributes to their JSX equivalents, is widely useful outside of this module. There are lots of modules on npm that implement this themselves, in more or less complete form — they would all benefit from sharing a small and focused package that does nothing but this conversion.

eslint-plugin-react probably has more, and more committed, users than most of the other modules. So if it were to spearhead adoption of a focused package, the package would no doubt stay up-to-date, which would be a great thing for all the other modules that would rely on it.

@noraesae has already created https://github.com/noraesae/react-attr-converter, with the clear intention of serving this purpose. It would be awesome if no-unknown-property could use react-attr-converter, and eslint-plugin-react users could contribute to its upkeep. 

What do you think? I could PR the switch if this sounds good.

**Comment by ljharb** [comment] 2017-06-14 02:18
I think that it makes much more sense for React to own this, than for anyone in the ecosystem to do so - since React has the same logic internally. `enzyme` could also benefit from this.

@gaearon et al, what do you think?

**Comment by lencioni** [comment] 2017-06-26 18:44
It seems like this might make sense for [jsx-ast-utils](https://github.com/evcohen/jsx-ast-utils). @evcohen thoughts?

**Comment by ljharb** [comment] 2017-06-26 21:10
Fwiw, this already exists in `airbnb-prop-types` - [`require('airbnb-prop-types/build/helpers/getComponentName')`](https://unpkg.com/airbnb-prop-types@2.7.0/build/helpers/getComponentName.js). It'd just be better if it was a canon React implementation instead.

**Comment by gaearon** [comment] 2017-06-26 22:17
In React we're trying to gradually move away from whitelists so I don't think we'll want to take on maintaining something like this (and thus making it seem like we encourage libraries to use it). It makes sense for tools but I think the community would do a better job of maintaining lists for ESLint etc. We don't often change those.

**Comment by ljharb** [comment] 2017-06-26 22:51
@gaearon in general terms, as the community creates packages like that, would react be willing to commit to adding regression tests for them, to prevent unknown breakage when react makes a new release? That's really the sole reason I think it'd be important to have it be "from React".

**Comment by gaearon** [comment] 2017-06-26 23:39
Can you create an issue in React repo? I'm not sure I fully understand what you're proposing.

**Comment by evcohen** [comment] 2017-06-27 01:41
@lencioni most of `jsx-ast-utils` is specific to the AST, but we have added whitelists before for [event handlers](https://github.com/evcohen/jsx-ast-utils#eventhandlers). Would be happy to maintain this list and function if it benefits the community!

**Comment by davidtheclark** [comment] 2017-06-27 02:03
@lencioni @evcohen: I'm not sure why https://github.com/noraesae/react-attr-converter doesn't do the job. It could be incorporated into `eslint-plugin-react`, `jsx-ast-utils`, etc. Seems preferable to me to have a single-focus package for this, which other projects can then depend on.

**Comment by ljharb** [comment] 2017-06-27 06:44
@gaearon https://github.com/facebook/react/issues/10051

**Comment by evcohen** [comment] 2017-06-27 13:26
@davidtheclark that works just fine! there are tradeoffs for both, but I'm cool with that just as long as whoever owns that package is committed to maintaining it.

**Comment by ljharb** [comment] 2022-02-04 00:59
Sadly, React decided on an approach that shifts the burden to the ecosystem instead of react itself.

react-attr-converter is archived now, so it's a good idea we didn't depend on it.

If there's common functionality between eslint-plugin-react and eslint-plugin-jsx-a11y, then jsx-ast-utils would be a great place for it.

**Closed by ljharb** 2022-02-04 00:59 UTC
