### ISSUE TITLE
Rule request: Prevent unused prop in component definition

### ISSUE THREAD

**Issue by mocheng** [yannickcr/eslint-plugin-react#583] opened 2016-05-03 05:12 UTC
Suppose propTypes states one prop to be `isRequired`, but that prop is not used in component definition. This could be a problem.

For the time being, React reports a warning like 

> Warning: Failed propType: Required prop `xxxxxx` was not specified in `XXXXXX`. Check the render method of `Connect(XXXXX)`

It would be nice to have it reported as error in lint phase.

**Comment by lo1tuma** [comment] 2016-05-03 16:26
Looks like a duplicate of #226.

**Comment by ljharb** [comment] 2016-05-03 16:28
This is similar to #226 but slightly different in that it's separately warning on missing *required* props. I'll leave both open, but I think both could be handled by one rule with an option to restrict enforcement to missing required props.

**Comment by yannickcr** [comment] 2016-05-08 19:19
Yes, same rule as #226. I am not convinced of the utility for an option to only warn on required props though. We can discuss it in #226.

**Closed by yannickcr** 2016-05-08 19:19 UTC
