### ISSUE TITLE
prop-types set to: 0 but still getting warnings about missing props validation

### ISSUE THREAD

**Issue by mladenp** [yannickcr/eslint-plugin-react#987] opened 2016-12-02 11:24 UTC
I am extending `eslint:recommended` and `plugin:react/recommended` and overriding rules like:
`  "rules": {
    "no-unused-vars": [0],
    "prop-types": [0],
    "eol-last": [0],
    "no-mixed-requires": [0],
    "no-underscore-dangle": [0]
  }
`
But i am still getting **missing prop types validation** warnings in WebStorm

**Comment by ljharb** [comment] 2016-12-02 16:24
Dupe of #988.

**Closed by ljharb** 2016-12-02 16:24 UTC
