### ISSUE TITLE
PropTypes.elementType is marked as error

### ISSUE THREAD

**Issue by LAITONEN** [yannickcr/eslint-plugin-react#2368] opened 2019-08-01 20:01 UTC
Using PropTypes.elementType with prop-types and eslint-react-plugin latest versions is being marked as error:

`Typo in declared prop type: elementType eslint(react/no-typos)`

**Comment by ljharb** [comment] 2019-08-01 20:29
it’s element Type, not elemen Type - however, be sure you have an updated version of the prop-types lib, since that’s where the rule gets its list of correct names.

**Comment by LAITONEN** [comment] 2019-08-01 21:04
@ljharb Thanks, but that was just a typo :) Updated the post.

According to package.json of prop-types node-module, the version is indeed latest.

**Comment by ljharb** [comment] 2019-08-01 21:45
What version of eslint-plugin-react do you have? That also needs to be on latest to get the version that no longer hardcodes the list.

**Comment by LAITONEN** [comment] 2019-08-02 12:08
@ljharb from package.json:

```
  "_from": "eslint-plugin-react@latest",
  "_id": "eslint-plugin-react@7.14.3",
```

**Comment by ljharb** [comment] 2019-08-02 14:34
Can you share the code that’s erroring?

**Comment by LAITONEN** [comment] 2019-08-03 14:17
Sure!
```
Component.propTypes = {
  // eslint-disable-next-line react/no-typos
  prop: PropTypes.elementType
}
```

**Comment by ljharb** [comment] 2019-08-03 15:11
This is the same issue as https://github.com/yannickcr/eslint-plugin-react/issues/2188#issuecomment-468991235, so I’m really not sure what’s happening.

Note, you may have duplicate prop-types libs in your graph; don’t just open up the package.json, check your lockfile, and try `npm ls | grep prop-types`

**Comment by dreamsparkx** [comment] 2019-10-01 12:18
I am having the same problem

**Comment by ljharb** [comment] 2019-10-01 12:49
I'm going to close this as a duplicate of https://github.com/yannickcr/eslint-plugin-react/issues/2188#issuecomment-468991235.

As long as you have a `prop-types` installed that has `elementType`, this plugin will pick it up.

**Closed by ljharb** 2019-10-01 12:49 UTC
