### ISSUE TITLE
"ESLint: Error while loading rule 'react/display-name': Cannot find module 'react' from '/home/...'.

### ISSUE THREAD

**Issue by sgehrman** [yannickcr/eslint-plugin-react#2346] opened 2019-07-12 22:41 UTC
This version works:
"eslint-plugin-react": "7.11.1",

But new versions are broken.  My project is a bit non standard.  We have the package.json inside the source folder, so it seems the new versions don't find it in this case, but it has worked fine when using 7.11.1

**Comment by ljharb** [comment] 2019-07-12 23:45
are you on eslint 5 or 6? eslint 6 made some changes that tend to force standard configurations.

**Comment by sgehrman** [comment] 2019-07-15 18:54
I'm using 5.16.0

**Comment by ljharb** [comment] 2019-07-15 20:29
Can you explain a bit about your project layout, including where package.json and your eslint config lives, and where you ran the eslint command?

**Comment by alyrik** [comment] 2019-07-16 07:28
@sgehrman, I faced the same today. The cause was a corrupted `react` module in `node_modules`. It was partly deleted after installing `eslint-plugin-jsx-a11y`. Try to remove `node_modules` and reinstall it.

**Comment by EddyLuten** [comment] 2019-07-16 20:17
I am facing the same issue as OP (using eslint 5.16.0), downgrading to 7.11.1 worked for me as well.

**Comment by HofmannZ** [comment] 2019-07-18 09:51
I can confirm downgrading `eslint-plugin-react` to `7.11.1` while running ESLint `6.0.1` is a temporary work around.

The following PRs have been merged since `7.11.1`: #2225, #2137, #2109, #2002 and #1098.

**Comment by lbebber** [comment] 2019-07-18 21:38
As for myself, downgrading to `7.13.0` was enough. This issue starts appearing at `7.14.0`.

**Comment by lbebber** [comment] 2019-07-18 22:13
It seems the error is being caused by this commit specifically https://github.com/golopot/eslint-plugin-react/commit/bdd61922d373f71d8

**Comment by ljharb** [comment] 2019-07-18 23:58
ah - that might be fixed in #2336 / #2276, just unreleased.

**Comment by michaellopez** [comment] 2019-07-21 00:13
@ljharb any info on when a new release containing that fix will be published?

**Comment by yannickcr** [comment] 2019-07-22 22:57
@michaellopez I just published `v7.14.3` with the fix 🙂

**Closed** 2019-07-22 22:59 UTC
Labels: bug, help wanted, question

**Comment by geoseong** [comment] 2019-09-19 05:35
I just remove and reinstall, problem solved. my version is `7.12.4`

```
"eslint-plugin-react": "^7.12.4",
```

**Comment by devuxer** [comment] 2024-02-22 06:08
I just ran into this with the latest version. I tried (1) restarting VSCode and (2) deleting node_modules and re-running `npm install`, but neither of those helped. Finally, I tried downgrading to 7.11.1, running eslint, then updating to latest, and running again. This worked!

(Perhaps the issue is caused by trying to run eslint with a much newer version than it was previously run. Maybe you need to run with a _somewhat_ newer version before just suddenly upgrading to the latest version like a crazy person. I'm sorry, I'm just making this up. I have no idea 🤷‍♂️🤷‍♂️🤷‍♂️.)

**Comment by ljharb** [comment] 2024-02-22 17:51
@devuxer you should be able to upgrade to latest eslint 7 just fine. upgrading to eslint 8 might be trickier.
