### ISSUE TITLE
Add a rule prefer-covariant-props

### ISSUE THREAD

**Issue by julienw** [yannickcr/eslint-plugin-react#1454] opened 2017-09-28 16:01 UTC
With react and flow, it's very common to type props like this:

```javascript
type Props = {
  prop1: string,
  prop2: number
};
```

However this makes it possible to write to the props object, like this: `this.props.prop1 = 'foo'` which is to be avoided.
To force this with flow, the solution is to use covariant properties:
```javascript
type Props = {
  +prop1: string,
  +prop2: number
};
```

It would be useful to have an eslint rule to force this pattern.

**Comment by ljharb** [comment] 2017-09-28 17:56
I'm a bit hesitant to have Flow-only rules in a non-flow-specific eslint plugin, but I agree that such a rule would be a good thing to have if using Flow.

**Comment by julienw** [comment] 2017-09-28 20:18
Yeah I hesitated between filing this or in eslint-plugin-flowtype, but I thought it was more react-specific than flow-specific :)

**Comment by EvHaus** [comment] 2019-01-04 17:34
Closing this as a duplicate of #1869

**Closed by EvHaus** 2019-01-04 17:34 UTC
Labels: flow, new rule, question

**Comment by julienw** [comment] 2019-01-04 18:02
:+1:
