### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by misund** [yannickcr/eslint-plugin-react#1936] opened 2018-08-14 17:26 UTC
Getting the error `Cannot read property 'name' of undefined` after upgrade from 7.9.1 to 7.11.0.

Example of source code that will trigger the crash:
```jsx
import React from 'react';
import propTypes from 'prop-types';

const Foo = ({ bar, children }) => <div className={bar}>{children}</div>;
const Baz = ({...rest})=> <Foo {...rest}>Baz</Foo>;

Foo.propTypes = {
	bar: propTypes.string,
};
Baz.propTypes = Foo.propTypes;

export {
	Foo,
	Baz,
};
```

`Baz.propTypes = Foo.propTypes;` seems to be the trigger.

**Comment by ljharb** [comment] 2018-08-14 17:31
Duplicate of #1928.

**Closed by ljharb** 2018-08-14 17:31 UTC
