### ISSUE TITLE
Allow default arguments on functional component to count as defaultProps

### ISSUE THREAD

**Issue by singpolyma-shopify** [yannickcr/eslint-plugin-react#1188] opened 2017-05-11 15:37 UTC
When using Flow, this is the suggested pattern (https://flow.org/en/docs/frameworks/react/):

```
type CardProps = { wrapInSection?: bool };

function Card({ wrapInSection = true }: CardProps) {
    // ...
}
```

But eslint says:

` error  propType "wrapInSection" is not required, but has no corresponding defaultProp declaration`

**Comment by ljharb** [comment] 2017-05-11 16:02
Duplicate of #1184

**Closed by ljharb** 2017-05-11 16:02 UTC
