### ISSUE TITLE
rule proposal: require setState called w/existing state expression use func instead

### ISSUE THREAD

**Issue by dmose** [yannickcr/eslint-plugin-react#1056] opened 2017-02-01 16:14 UTC
In particular https://medium.com/@shopsifter/using-a-function-in-setstate-instead-of-an-object-1f5cfd6e55d1#.vbbxvfsd4 describes the problem that can be avoided here.

**Comment by ljharb** [comment] 2017-02-01 16:58
This is actually likely to become very important with React Fiber, so I think this is a good idea for a rule (specifically, if you use a value from `this.state` in your `setState` call, you should be passing a function to `setState` instead of an object)

**Comment by lencioni** [comment] 2017-02-01 18:24
What should such a rule be named?

**Comment by ljharb** [comment] 2017-02-01 18:32
`no-set-state-using-this-state`?

**Comment by lencioni** [comment] 2017-02-01 18:38
That's not quite right though, since with the callback version you are still using `setState` and `this.state`. It would need to be something like `no-set-state-object-using-this-state` but that feels a little verbose--but maybe that's the best we can do?

**Comment by ljharb** [comment] 2017-02-01 19:07
With the callback version, you're using `prevState`, *not* `this.state`, that's the whole point. I'm fine with your more verbose name tho.

**Comment by lencioni** [comment] 2017-02-01 19:11
Ah, you are absolutely correct. Your suggestion sounds good to me then.

**Comment by adnasa** [comment] 2017-02-15 00:55
btw guys, isn't this [thread](943) discussing the same proposal?

**Comment by lencioni** [comment] 2017-02-15 01:02
Looks like it. Closing this one as a duplicate of #943.

**Closed by lencioni** 2017-02-15 01:02 UTC
Labels: new rule, question
