### ISSUE TITLE
Add autofixing

### ISSUE THREAD

**Issue by Daniel15** [yannickcr/eslint-plugin-react#304] opened 2015-11-11 01:38 UTC
ESLint 1.4 added support for autofixes (see http://eslint.org/blog/2015/09/eslint-v1.4.0-released/). This is a pretty core feature of a linter, so I'm glad they're finally adding support for it :smile:. Autofixing allows rules to also specify ways to automatically fix the rule.  For example, an autofix for `jsx-sort-props` could have an autofix that would sort the props in the correct order.

**Comment by yannickcr** [comment] 2015-11-16 21:35
Duplicate of #245

**Closed by yannickcr** 2015-11-16 21:35 UTC
