### ISSUE TITLE
Error in prop-types rule: key is undefined 

### ISSUE THREAD

**Issue by Lapixx** [yannickcr/eslint-plugin-react#269] opened 2015-10-22 11:42 UTC
We just encountered an error in the `prop-types` rule while ESLinting a JSX file. I'm unable to share the full source, but will try to pinpoint the part where the rule fails exactly.

In the meantime, this is the full stack trace:

```
/usr/local/lib/node_modules/eslint-plugin-react/lib/rules/prop-types.js:187
return key.type === 'Identifier' ? key.name : key.value;
             ^

TypeError: Cannot read property 'type' of undefined
   at getKeyValue (/usr/local/lib/node_modules/eslint-plugin-react/lib/rules/prop-types.js:187:15)
   at markPropTypesAsUsed (/usr/local/lib/node_modules/eslint-plugin-react/lib/rules/prop-types.js:366:11)
   at EventEmitter.MemberExpression (/usr/local/lib/node_modules/eslint-plugin-react/lib/rules/prop-types.js:547:11)
   at emitOne (events.js:82:20)
   at EventEmitter.emit (events.js:169:7)
   at NodeEventGenerator.enterNode (/usr/local/lib/node_modules/eslint/lib/util/node-event-generator.js:42:22)
   at CommentEventGenerator.enterNode (/usr/local/lib/node_modules/eslint/lib/util/comment-event-generator.js:98:23)
   at Controller.controller.traverse.enter (/usr/local/lib/node_modules/eslint/lib/eslint.js:782:36)
   at Controller.__execute (/usr/local/lib/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
   at Controller.traverse (/usr/local/lib/node_modules/eslint/node_modules/estraverse/estraverse.js:495:28)
```

Also, ESLint exited with code 0 in the end, which to me looks not really desirable if one of the rules fails, although I assume that's more of an issue of ESLint itself.

**Comment by yannickcr** [comment] 2015-10-25 11:57
It would be a great help for us if you can track down the code responsible for the crash, maybe by running ESLint on one directory at a time until you find the file that trigger this error ?

**Comment by Lapixx** [comment] 2015-10-27 17:39
So the problem seems to be specifically related to the rest spread feature we use in our JSX files:
```
let { firstKey, ...rest } = this.props;
```

Works fine. But this:

```
let { ...rest } = this.props;
```

Results in the TypeError as shown in my first post.

I've seen some other issues regarding the `experimentalObjectRestSpread` feature in the ESLint repository itself, (e.g. using `<ComponentName {...other} prop={firstKey} />` reports `other` as not defined), so this might actually be related.

However, I'm pretty sure the `prop-types` shouldn't break in this case.

**Comment by yannickcr** [comment] 2015-11-05 22:06
I was not able to reproduce the error, but it should be fixed in `v3.7.1`.

If it is not the case, re-open this issue and add the complete code sample that trigger the crash.

**Comment by Lapixx** [comment] 2015-11-12 12:13
Hey, sorry to get back at you this late. I was able to reproduce this bug here: [Lapixx/a30830afe8408756d254](https://gist.github.com/Lapixx/a30830afe8408756d254)

Running eslint **1.5.1** and eslint-plugin-react **3.8.0**

**Comment by yannickcr** [comment] 2015-11-16 23:09
Thanks for your test case, I can reproduce it now.
I will fix this.

**Closed** 2015-11-16 23:21 UTC
Labels: bug, rule
