### ISSUE TITLE
Referencing with PropTypes.shape

### ISSUE THREAD

**Issue by vutran** [yannickcr/eslint-plugin-react#833] opened 2016-09-14 17:26 UTC
When referencing shaped PropTypes, it is producing `react/no-unused-prop-types`.

See below:

``` js
const myComponent = ({ bar }) => (
  <div>
    {bar.a}
    {bar.n}
    {bar.c}
  </div>
);

myComponent.propTypes = {
  bar: PropTypes.shape({
    a: PropTypes.string, // react-no-unused-prop-types
    b: PropTypes.string, // react-no-unused-prop-types
    c: PropTypes.string, // react-no-unused-prop-types
  }),
};
```

Also errors for:

``` js
const myComponent = (props) => {
  const bar = props.bar; // produces errors
  // const { bar } = props; // produce errors
  return (
    <div>
      {bar.a}
      {bar.n}
      {bar.c}
    </div>
  );
}
```

We would have to use it directly to avoid errors:

``` js
const myComponent = (props) => {
  return (
    <div>
      {props.bar.a}
      {props.bar.n}
      {props.bar.c}
    </div>
  );
}
```

**Comment by EvNaverniouk** [comment] 2016-09-30 22:52
Duplicate of #871. 

The `no-unused-prop-types` rule does not support `shape` props at the moment as such detection is very difficult. If you use shape props, I recommend setting the `skipShapeProps` option to `true` on the rule.

**Comment by ljharb** [comment] 2016-09-30 23:47
This is still a bug. If it doesn't support shape props, it should skip them in all cases.

**Comment by tleunen** [comment] 2016-11-02 02:53
Any update on this? Can we make a patch to skip them until a better detection is done?

**Comment by DianaSuvorova** [comment] 2017-07-28 20:43
if the rule is using `options: [{skipShapeProps: true}]` (it is default), it would skip validation. Should be closed.

**Comment by ljharb** [comment] 2017-07-28 21:14
Yes, but if it's using `false`, this should work.

**Closed** 2019-06-13 02:38 UTC
Labels: bug
