### ISSUE TITLE
Null Point Exception on 3.7.0 Release

### ISSUE THREAD

**Issue by mjrussell** [yannickcr/eslint-plugin-react#289] opened 2015-11-05 01:22 UTC
```
> eslint src/

/Users/matt/Projects/event-tracker/client/node_modules/eslint-plugin-react/lib/util/Components.js:113
      return sourceCode.getText(node.parent.callee) === 'React.createClass';
                                           ^

TypeError: Cannot read property 'callee' of null
    at Object.context.react.isES5Component (/Users/matt/Projects/event-tracker/client/node_modules/eslint-plugin-react/lib/util/Components.js:113:44)
    at Object.context.react.getParentES5Component (/Users/matt/Projects/event-tracker/client/node_modules/eslint-plugin-react/lib/util/Components.js:183:35)
    at Object.context.react.getParentComponent (/Users/matt/Projects/event-tracker/client/node_modules/eslint-plugin-react/lib/util/Components.js:170:23)
    at Object.detectionInstructions.FunctionDeclaration (/Users/matt/Projects/event-tracker/client/node_modules/eslint-plugin-react/lib/util/Components.js:337:28)
    at EventEmitter.updatedRuleInstructions.(anonymous function) (/Users/matt/Projects/event-tracker/client/node_modules/eslint-plugin-react/lib/util/Components.js:375:41)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.enterNode (/Users/matt/Projects/event-tracker/client/node_modules/eslint/lib/util/node-event-generator.js:42:22)
    at CommentEventGenerator.enterNode (/Users/matt/Projects/event-tracker/client/node_modules/eslint/lib/util/comment-event-generator.js:98:23)
    at Controller.controller.traverse.enter (/Users/matt/Projects/event-tracker/client/node_modules/eslint/lib/eslint.js:782:36)
```

Everything works great on 3.6.x

**Comment by yannickcr** [comment] 2015-11-05 01:23
Duplicate of #286

**Closed by yannickcr** 2015-11-05 01:23 UTC

**Comment by mjrussell** [comment] 2015-11-05 01:24
Ah sorry for the dup, was only looking at the open issues

**Comment by yannickcr** [comment] 2015-11-05 01:26
No problem :) I'm preparing a patch release, it should be published in next coming hour.

**Comment by luisrudge** [comment] 2015-11-05 02:10
Thanks @yannickcr!
