### ISSUE TITLE
TypeError raised by forbid-prop-types

### ISSUE THREAD

**Issue by tinder-devon-strawn** [yannickcr/eslint-plugin-react#2684] opened 2020-06-29 19:44 UTC
Seems to be introduced in 7.20.1, probably caused by #2676

[`checkProperties()` in `forbid-prop-types.js`](https://github.com/yannickcr/eslint-plugin-react/blob/v7.20.1/lib/rules/forbid-prop-types.js#L90) throws an error when `declarations` arg is `undefined`:

    TypeError: Cannot read property 'forEach' of undefined
        at checkProperties (/Users/devons/Projects/scratch/node_modules/eslint-plugin-react/lib/rules/forbid-prop-types.js:95:20)
        at CallExpression (/Users/devons/Projects/scratch/node_modules/eslint-plugin-react/lib/rules/forbid-prop-types.js:185:11)
        at /Users/devons/Projects/scratch/node_modules/eslint/lib/util/safe-emitter.js:47:58
        at Array.forEach (<anonymous>)
        at Object.emit (/Users/devons/Projects/scratch/node_modules/eslint/lib/util/safe-emitter.js:47:38)
        at NodeEventGenerator.applySelector (/Users/devons/Projects/scratch/node_modules/eslint/lib/util/node-event-generator.js:251:26)
        at NodeEventGenerator.applySelectors (/Users/devons/Projects/scratch/node_modules/eslint/lib/util/node-event-generator.js:280:22)
        at NodeEventGenerator.enterNode (/Users/devons/Projects/scratch/node_modules/eslint/lib/util/node-event-generator.js:294:14)
        at CodePathAnalyzer.enterNode (/Users/devons/Projects/scratch/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:23)
        at Traverser.enter [as _enter] (/Users/devons/Projects/scratch/node_modules/eslint/lib/linter.js:865:28)

**Comment by ljharb** [comment] 2020-06-29 19:49
Duplicate of #2682; fix will be released later today.

**Closed by ljharb** 2020-06-29 19:49 UTC
