### ISSUE TITLE
Rule proposal: JavaScript Expression spacing

### ISSUE THREAD

**Issue by neciu** [yannickcr/eslint-plugin-react#1007] opened 2016-12-21 08:49 UTC
This rule should force adding/removing of spaces in JavaScript Expressions. 

Given the value of the rule is `always`:
1. Is wrong
```
...
  return (
    <div>
      {children}
    </div>
  );
...
```
2. Is ok
```
...
  return (
    <div>
      { children }
    </div>
  );
...
```

Given the value of the rule is `never`:
1. Is ok
```
...
  return (
    <div>
      {children}
    </div>
  );
...
```
2. Is wrong
```
...
  return (
    <div>
      { children }
    </div>
  );
...
```

**Comment by ljharb** [comment] 2016-12-21 09:05
This is a duplicate of https://github.com/yannickcr/eslint-plugin-react/issues/857#issuecomment-255827739

**Comment by fatfisz** [comment] 2017-06-11 17:32
This is fixed in #1177.

**Closed** 2017-06-11 18:18 UTC
