### ISSUE TITLE
Rule for no optional props without default values?

### ISSUE THREAD

**Issue by EdwardDrapkin** [yannickcr/eslint-plugin-react#673] opened 2016-07-11 08:03 UTC
Hello friends,

I was looking for a way to enforce a code quality guideline with eslint and seem to be unable.  Basically, we have a bunch of React components that define optional properties.  I'd like eslint to guarantee that all non required properties are required to have default values (e.g. if propTypes has a value of `foo: React.propTypes.string`, defaultProps has to have a key of foo set too).   Is this currently possible?

TIA!

**Comment by ljharb** [comment] 2016-07-11 17:43
This seems like the same as #305, and is definitely a duplicate of #528.

**Closed by ljharb** 2016-07-11 17:43 UTC
