### ISSUE TITLE
Why `self-closing-comp` allows empty divs?

### ISSUE THREAD

**Issue by alexfedoseev** [yannickcr/eslint-plugin-react#572] opened 2016-04-25 17:40 UTC
I noticed that [self-closing-comp](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/self-closing-comp.md) doesn't report empty divs (eg `<div></div>`). Is there any particular reason that it allows empty html tags? Or it's valid b/c it's valid html?

**Comment by ljharb** [comment] 2016-04-25 17:48
Seems like a bug to me. That should be `<div />`.

**Comment by alexfedoseev** [comment] 2016-04-25 19:05
@ljharb I'd be sure it is, if there wasn't this in the doc:

<img width="463" alt="screen shot 2016-04-25 at 21 56 39" src="https://cloud.githubusercontent.com/assets/4244251/14795349/cd1a0252-0b30-11e6-8731-8c453a7eee92.png">

**Comment by ljharb** [comment] 2016-04-25 20:26
That doesn't make much sense to me - but if it's documented, then it's not a bug.

However, I'd love to see an option added to this rule that requires self-closing tags for *every* kind of tag, including HTML tags. @yannickcr?

**Comment by yannickcr** [comment] 2016-04-25 20:39
This is the intended behavior. This rule only enforce empty React Components to be self-closed, and HTML tags are not concerned.

I think we could modify this rule to check all type of tags by default, then add some options to filter by type (components and/or HTML tags) if needed.

It seems to be the more logical behavior to me, but it will be a breaking change.

**Comment by ljharb** [comment] 2016-04-25 22:28
Airbnb's React styleguide requires every empty element to be self-closed.

Alternatively, we could add an option in a minor version, and then flip the default behavior later, in a major?

**Comment by gitim** [comment] 2016-05-14 13:53
Have the same issue. Is anybody already working on it? If not I'll prepare a pull request, which will add the option suggested by @ljharb to the rule.

**Closed** 2016-06-05 15:49 UTC
Labels: new rule, question

**Comment by GeoffGodwin** [comment] 2018-06-26 19:29
Just wanted to leave my comment in here for future developers reaching this page. `<div/>` is not a valid HTML 4.x tag. It's the only base HTML tag (that I know of) that cannot be legally self-closing. If you use a `<div/>` it can cause very strange issues that can bubble up through a variety of frameworks (looking at you jQuery) making it difficult to trace as it does not throw distinct errors. One particular example being in IE8 where it breaks the DOM tree fairly silently.

It is always better practice to use `<div></div>` even if no content exists between the tags.

As a note, `<div/>` is legitimate XHTML 1.x. However for the sake of compatibility across browsers and versions there is no reason to use it.

I realize this is ooooold world HTML but it's still very valid today. Cheers!

**Comment by ljharb** [comment] 2018-06-26 19:33
jsx isn’t quite html.

**Comment by GeoffGodwin** [comment] 2018-06-26 19:44
No arguments there, I just figure underlying it may be trying to generate a real DOM <div/> which would then cause problems. I haven't gone through the project to know how it's generating the actual DOM element so for all I know it's properly making <div></div> but I figured this was a good place to drop the knowledge in anyway.

**Comment by ljharb** [comment] 2018-06-26 20:55
lol, React generates proper HTML, that's not something anyone needs to worry about :-)
