### ISSUE TITLE
Rule treats all functions with (props) as stateless functions

### ISSUE THREAD

**Issue by turnerhayes** [yannickcr/eslint-plugin-react#1480] opened 2017-10-16 02:00 UTC
I'm not sure if this qualifies as a bug, but I have a stateless component function that delegates its rendering to other functions that happen to have the signature `function renderSomething(props)`, but are not in themselves meant to be components, just functions used to separate out functionality so that the component function doesn't get too huge.

Basically, something like this:

``` javascript
function renderIfLoggedIn(props) {
    return (<div>{props.username} stuff</div>);
}

function renderIfNotLoggedIn(props) {
    return (<div>other stuff</div>);
}

function MyStatelessComponent(props) {
    return props.isLoggedIn ?
            renderIfLoggedIn(props) :
            renderIfNotLoggedIn(props);
}

MyStatelessComponent.propTypes = {
    isLoggedIn: PropTypes.bool,
    username: PropTypes.string,
    ...other propTypes
};
```

When I lint the file, it throws an error that the prop `username` is missing from validation. It took me a while to realize that it was referring to the `renderIfLoggedIn()` function, because clearly `username` *is* in props validation for `MyStatelessComponent`, but `renderIfLoggedIn` has not `propTypes` at all.

If this were a class rather than a stateless component function, I would make `renderIfLoggedIn` and `renderIfNotLoggedIn` methods of the class and call them using `this`, but that obviously doesn't work so well with a function. I mean, I *could* add them to its prototype, but that seems slightly overkill.

I realize that there may not be any good way of making a distinction from the linter's perspective; the function *look* alike. Perhaps only asserting prop validation if the function is exported? That may not be ideal either, because I can imagine there could be use cases where someone actually wants to use stateless components local to the file and still have prop validation.

I can probably work around it either by changing the signatures of `renderIf[Not]LoggedIn` or making them instance methods via `prototype`, but I wanted to bring up the issue here anyway.

**Comment by ljharb** [comment] 2017-10-17 05:15
Basically any function that returns jsx is considered a component by this plugin, and conceptually, all your "render" methods should indeed be separate components with their own propTypes, defaultProps, and tests (if they're exported).

**Comment by ljharb** [comment] 2017-10-17 05:16
This is also a duplicate of #512.

**Closed by ljharb** 2017-10-17 05:16 UTC
