### ISSUE TITLE
Add rule enforcing `props` are passed to `super` in constructor

### ISSUE THREAD

**Issue by mericsson** [yannickcr/eslint-plugin-react#1620] opened 2017-12-22 01:07 UTC
Following the advice of the [React Docs react-component#constructor](https://reactjs.org/docs/react-component.html#constructor) it would be great if there was an eslint rule that would convert:

```js
constructor(props) {
  super();
  // ....
}
```

to:
```js
constructor(props) {
  super(props);
  // ....
}
```

So that we would catch cases where someone tries to use `this.props` before it is populated. Thank you!

**Comment by ljharb** [comment] 2017-12-22 02:57
Looks like a duplicate of #626

**Closed by ljharb** 2017-12-22 02:57 UTC

**Comment by joetidee** [comment] 2018-06-22 16:32
Has this rule been added?

**Comment by ljharb** [comment] 2018-06-23 05:19
@joetidee no, see #626.
