### ISSUE TITLE
Error: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by Odywan55** [yannickcr/eslint-plugin-react#642] opened 2016-06-17 16:11 UTC
Hello , have such error : 

TypeError: Cannot read property 'name' of undefined
    at EventEmitter.CallExpression (C:\Users\Rostyslav\Desktop\Last\node_modules\eslint-plugin-react\lib\rules\jsx-no-bind.js:23:24)
    at emitOne (events.js:95:20)
    at EventEmitter.emit (events.js:182:7)
    at NodeEventGenerator.enterNode (C:\Users\Rostyslav\Desktop\Last\node_modules\eslint\lib\util\node-event-generator.js:40:22)
    at CodePathAnalyzer.enterNode (C:\Users\Rostyslav\Desktop\Last\node_modules\eslint\lib\code-path-analysis\code-path-analyzer.js:607:23)
    at CommentEventGenerator.enterNode (C:\Users\Rostyslav\Desktop\Last\node_modules\eslint\lib\util\comment-event-generator.js:97:23)
    at Controller.traverser.traverse.enter (C:\Users\Rostyslav\Desktop\Last\node_modules\eslint\lib\eslint.js:905:36)
    at Controller.__execute (C:\Users\Rostyslav\Desktop\Last\node_modules\estraverse\estraverse.js:397:31)
    at Controller.traverse (C:\Users\Rostyslav\Desktop\Last\node_modules\estraverse\estraverse.js:501:28)
    at Controller.Traverser.controller.traverse (C:\Users\Rostyslav\Desktop\Last\node_modules\eslint\lib\util\traverser.js:36:33)

"eslint": "^2.12.0"
"eslint-plugin-react": "^5.2.1"

**Comment by ljharb** [comment] 2016-06-17 17:14
Duplicate of #641.

**Closed by ljharb** 2016-06-17 17:14 UTC
