### ISSUE TITLE
Cannot read property 'type' of null

### ISSUE THREAD

**Issue by danrot** [yannickcr/eslint-plugin-react#1550] opened 2017-11-19 09:14 UTC
Since yesterday there is an error happening on our build, which seems to be related with the latest 7.5 release: https://travis-ci.org/sulu/sulu/jobs/304057844#L3406

I don't really know which part of my code might be responsible for this, but if I get some hints on how to find out I might be able to do that :-)

**Comment by jseminck** [comment] 2017-11-19 09:19
This is already reported ( https://github.com/yannickcr/eslint-plugin-react/issues/1543 ) and a fix has been merged ( https://github.com/yannickcr/eslint-plugin-react/pull/1544 ).

Hopefully a v7.5.1 will go out later today!

Thanks for understanding 👍

**Comment by danrot** [comment] 2017-11-19 09:41
Great! Thanks a lot 😃

**Comment by ljharb** [comment] 2017-11-19 14:21
Duplicate of #1543.

**Closed by ljharb** 2017-11-19 14:21 UTC
