### ISSUE TITLE
eslint crashes when using rest syntax in component params

### ISSUE THREAD

**Issue by PeterPanen** [yannickcr/eslint-plugin-react#2817] opened 2020-10-02 07:32 UTC
I am running newest eslint 7.10.0 and eslint-plugin-react 7.21.2, and i'm having this weird issue in functional components where eslint crashes whenever i use rest like below:

```javascript
// test.js
import React from "react"

const Header = ({ text, ...other }) => {
  return <h1>Test</h1>
}
```

eslint produces the following error:
```
Oops! Something went wrong! :(

ESLint: 7.10.0

TypeError: Cannot read property 'type' of undefined
Occurred while linting /home/username/Webapps/project/src/components/ApplicantViewerModal/test.js:1
    at /home/username/Webapps/project/node_modules/eslint-plugin-react/lib/rules/prop-types.js:156:39
    at Array.forEach (<anonymous>)
    at /home/username/Webapps/project/node_modules/eslint-plugin-react/lib/rules/prop-types.js:152:26
    at Array.forEach (<anonymous>)
    at isDeclaredInDestructuredParam (/home/username/Webapps/project/node_modules/eslint-plugin-react/lib/rules/prop-types.js:147:14)
    at isDeclaredInComponent (/home/username/Webapps/project/node_modules/eslint-plugin-react/lib/rules/prop-types.js:189:18)
    at /home/username/Webapps/project/node_modules/eslint-plugin-react/lib/rules/prop-types.js:204:13
    at Array.filter (<anonymous>)
    at reportUndeclaredPropTypes (/home/username/Webapps/project/node_modules/eslint-plugin-react/lib/rules/prop-types.js:201:51)
    at /home/username/Webapps/project/node_modules/eslint-plugin-react/lib/rules/prop-types.js:226:11
```

However, if i just pull the rest syntax down into the function body, everything works fine:
```javascript
// test.js
import React from 'react'

const Header = props => {
  const { text, ...other } = props
  return <h1>Test</h1>
}
```

**Comment by ljharb** [comment] 2020-10-02 07:37
Duplicate of #2816. Duplicate of #2810. Duplicate of #2806. Duplicate of #2804.

**Closed by ljharb** 2020-10-02 07:37 UTC

**Comment by PeterPanen** [comment] 2020-10-02 07:44
Oh, sorry i thought i had been looking thoroughly for duplicates and was slowly becoming insane haha xD
Thanks in advance!

**Comment by ljharb** [comment] 2020-10-02 17:36
np, i'll try to get a release out soon.
