### ISSUE TITLE
Rule proposal - no-inline-styles

### ISSUE THREAD

**Issue by xurei** [yannickcr/eslint-plugin-react#1325] opened 2017-07-27 14:20 UTC
From https://github.com/Intellicode/eslint-plugin-react-native/blob/master/docs/rules/no-inline-styles.md

The plugin can be installed for a wb project, but it feels hacky...

**Comment by jseminck** [comment] 2017-07-31 04:59
If the rule would be added to `eslint-plugin-react` then I feel that it should be removed from `eslint-plugin-react-native`. Having the same rule existing two times within the ecosystem is just confusing.

That particular rule indeed doesn't seem exclusive to React-Native so it may belong better within this plugin. I assume RN developers do use this plugin for their React linting?

Mostly up to other contributors and the owner of `eslint-plugin-react-native` to make that decision though.

**Comment by ellt92** [comment] 2018-04-16 10:58
This would be useful while using styled-components. Would be great to see this in the react plugin rather than the react-native plugin.

**Comment by ljharb** [comment] 2018-04-16 14:39
Closing as a duplicate of #327

**Closed by ljharb** 2018-04-16 14:39 UTC

**Comment by gerbus** [comment] 2020-03-17 15:30
It seems strange to have closed this as a duplicate of #327. #327 has nothing to do with adding this rule to `eslint-plugin-react`.
