### ISSUE TITLE
jsx-sort-props breaks on long props with sortable as one of props --fix

### ISSUE THREAD

**Issue by austinamorusocfc** [yannickcr/eslint-plugin-react#1937] opened 2018-08-14 22:48 UTC
this component will always break on eslint fix

```
<HeaderCell
				sortable={true}
				allowSort={allowSort}
				downImage={downImage}
				key={key}
				sortAscending={sortAscending}
				sortImageHeight={sortImageHeight}
				sortImageWidth={sortImageWidth}
				sortKey={sortKey}
				sortOnKey={sortOnKey}
				style={style}
				textStyle={headerTextStyle}
				title={title}
				upImage={upImage}
			/>
```

**Comment by ljharb** [comment] 2018-08-15 05:31
What does "breaks" mean?

**Comment by alexzherdev** [comment] 2018-08-18 18:14
This is duplicate of #1922, it breaks in the same way. Looking at the tests, that rule isn't handling multiline props at all 😕

**Comment by ljharb** [comment] 2018-08-18 21:44
Closing as a duplicate of #1922, then.

**Closed by ljharb** 2018-08-18 21:44 UTC
