### ISSUE TITLE
no-typos crash

### ISSUE THREAD

**Issue by alexlrobertson** [yannickcr/eslint-plugin-react#1639] opened 2018-01-11 16:01 UTC
I encountered a crash when linting a file with a bad prop type while using the latest version of the plugin:

```
MyComponent.propTypes = {
  item: PropTypes.shape()
};
```

```
Cannot read property 'type' of undefined
TypeError: Cannot read property 'type' of undefined
    at checkValidPropObject (/Users/alex/project/node_modules/eslint-plugin-react/lib/rules/no-typos.js:76:15)
    at checkValidProp (/Users/alex/project/node_modules/eslint-plugin-react/lib/rules/no-typos.js:65:11)
    at node.properties.forEach.prop (/Users/alex/project/node_modules/eslint-plugin-react/lib/rules/no-typos.js:77:41)
    at Array.forEach (native)
    at checkValidPropObject (/Users/alex/project/node_modules/eslint-plugin-react/lib/rules/no-typos.js:77:25)
    at reportErrorIfClassPropertyCasingTypo (/Users/alex/project/node_modules/eslint-plugin-react/lib/rules/no-typos.js:85:9)
    at MemberExpression (/Users/alex/project/node_modules/eslint-plugin-react/lib/rules/no-typos.js:135:11)
    at listeners.(anonymous function).forEach.listener (/Users/alex/project/node_modules/eslint/lib/util/safe-emitter.js:47:58)
    at Array.forEach (native)
    at Object.emit (/Users/alex/project/node_modules/eslint/lib/util/safe-emitter.js:47:38)
```

**Comment by ljharb** [comment] 2018-01-12 00:56
This is a duplicate of #1471 and is fixed in the next release.

**Closed by ljharb** 2018-01-12 00:56 UTC
