### ISSUE TITLE
[rule-proposal] function-component-definition

### ISSUE THREAD

**Issue by Stefanwullems** [yannickcr/eslint-plugin-react#2412] opened 2019-09-17 21:52 UTC
When `react/arrow-function-component

optional config: 
- `when: 'always'  | 'never'`default is `always`

if `when` is set to `always` it will show a warning if a function component is not an arrow function.
If `when` is set to `never` it will show a warning if a function component is not a regular function.

**Comment by ljharb** [comment] 2019-09-18 02:31
Duplicate of #412 and #690.

**Closed by ljharb** 2019-09-18 02:31 UTC
Labels: new rule
