### ISSUE TITLE
Error while using Control.text from 'react-redux-form'

### ISSUE THREAD

**Issue by JotSinghChawla** [yannickcr/eslint-plugin-react#2932] opened 2021-02-24 10:21 UTC
Hey, I am using **_Control.text_ from 'react-redux-form'**
And I am getting an error
 `Imported JSX component select must be in PascalCase or SCREAMING_SNAKE_CASE `

Can someone please help me resolve this issue?
I referred to this [https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-pascal-case.md](url) but it doesn't help 
I know the issue is in the naming convention of 'Control.text' but there isn't any solution in the official document of Redux.

**Comment by ljharb** [comment] 2021-02-24 16:25
This is intentional, but the recently merged and unreleased #2917 will provide you with an option that allows it.

Thus, this is a duplicate of #2914.

**Closed by ljharb** 2021-02-24 16:25 UTC
