### ISSUE TITLE
Error: VariableDeclarator ASTNodes are not handled by markPropTypesAsUsed

### ISSUE THREAD

**Issue by janryWang** [yannickcr/eslint-plugin-react#2322] opened 2019-06-24 04:16 UTC
```
const Box = ({fieldItem})=>{
   const { key, title } = fieldItem //this will throw error
   return ....
}

```

**Comment by golopot** [comment] 2019-06-24 04:19
Duplicate of #2319. Fix is merged in master but waiting for release.

**Comment by janryWang** [comment] 2019-06-24 04:37
ok, thanks

**Comment by janryWang** [comment] 2019-06-24 06:34
When is it possible to release this fixed version? @ljharb

**Comment by ljharb** [comment] 2019-06-24 06:47
Not sure yet; but issues remain closed when it's fixed in master, not when it's released.

**Closed by ljharb** 2019-06-24 06:47 UTC

**Comment by rum2code** [comment] 2019-06-24 08:03
I temporarily downgraded to version 7.13.0, I'm confused why webstorm's eslint plug-in failed

**Comment by rum2code** [comment] 2019-06-24 09:47
I remove .idea, and restart, ws working correctly
