### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by wmzy** [yannickcr/eslint-plugin-react#859] opened 2016-09-21 03:23 UTC
eslint-plugin-react@6.0.0 

error:
```bash
TypeError: Cannot read property 'length' of undefined
    at Object.utils.findReturnStatement (/home/zlt/project/mae-fe/node_modules/eslint-plugin-react/lib/util/Components.js:267:35)
    at Object.utils.isReturningJSX (/home/zlt/project/mae-fe/node_modules/eslint-plugin-react/lib/util/Components.js:219:24)
    at EventEmitter.CallExpression (/home/zlt/project/mae-fe/node_modules/eslint-plugin-react/lib/rules/jsx-no-bind.js:62:23)
    at emitOne (events.js:95:20)
    at EventEmitter.emit (events.js:182:7)
    at NodeEventGenerator.enterNode (/home/zlt/project/mae-fe/node_modules/eslint/lib/util/node-event-generator.js:40:22)
    at CodePathAnalyzer.enterNode (/home/zlt/project/mae-fe/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:23)
    at CommentEventGenerator.enterNode (/home/zlt/project/mae-fe/node_modules/eslint/lib/util/comment-event-generator.js:97:23)
    at Controller.traverser.traverse.enter (/home/zlt/project/mae-fe/node_modules/eslint/lib/eslint.js:903:36)
    at Controller.__execute (/home/zlt/project/mae-fe/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/home/zlt/project/mae-fe/node_modules/eslint/node_modules/estraverse/estraverse.js:501:28)
```
code:
```jsx
[
...
      {
        ...
        render: (write, user) =>
          (<Switch
            name="write"
            checked={write}
            onChange={this.handleChangeContactPerm.bind(this, user, 'write')}
          />)
      }
]
```

If I delete the line 
```jsx
            onChange={this.handleChangeContactPerm.bind(this, user, 'write')}
```
everything will be OK

**Comment by ljharb** [comment] 2016-09-21 03:59
@wmzy if you upgrade to v6.3.0 does this still happen?

**Comment by wmzy** [comment] 2016-09-21 05:57
The problem happened on v6.3.0 too.
```bash
Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at Object.utils.findReturnStatement (/home/zlt/project/mae-fe/node_modules/eslint-plugin-react/lib/util/Components.js:281:35)
    at Object.utils.isReturningJSX (/home/zlt/project/mae-fe/node_modules/eslint-plugin-react/lib/util/Components.js:233:24)
    at EventEmitter.CallExpression (/home/zlt/project/mae-fe/node_modules/eslint-plugin-react/lib/rules/jsx-no-bind.js:62:23)
    at emitOne (events.js:95:20)
    at EventEmitter.emit (events.js:182:7)
    at NodeEventGenerator.enterNode (/home/zlt/project/mae-fe/node_modules/eslint/lib/util/node-event-generator.js:40:22)
    at CodePathAnalyzer.enterNode (/home/zlt/project/mae-fe/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:23)
    at CommentEventGenerator.enterNode (/home/zlt/project/mae-fe/node_modules/eslint/lib/util/comment-event-generator.js:97:23)
    at Controller.traverser.traverse.enter (/home/zlt/project/mae-fe/node_modules/eslint/lib/eslint.js:903:36)
    at Controller.__execute (/home/zlt/project/mae-fe/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/home/zlt/project/mae-fe/node_modules/eslint/node_modules/estraverse/estraverse.js:501:28)
```

**Comment by yannickcr** [comment] 2016-09-21 08:49
Duplicate of #854

**Closed by yannickcr** 2016-09-21 08:49 UTC
Labels: bug
