### ISSUE TITLE
`no-unused-prop-types` and `getDerivedStateFromProps`

### ISSUE THREAD

**Issue by Hypnosphi** [yannickcr/eslint-plugin-react#1751] opened 2018-03-30 00:15 UTC
`no-unused-prop-types` should take into account usages from [new React lifecycles](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html#new-lifecycle-getderivedstatefromprops)

**Comment by teameh** [comment] 2018-03-30 10:51
Looks like it's coming up, PR is already merged: https://github.com/yannickcr/eslint-plugin-react/pull/1681 

When will this land?

**Comment by Hypnosphi** [comment] 2018-03-30 10:59
Looks like it doesn't include `getSnapshotBeforeUpdate`

**Comment by pkuczynski** [comment] 2018-04-11 15:33
When will this be released?

**Comment by jjaburke91** [comment] 2018-04-19 11:51
+1 for this

**Comment by jinliming2** [comment] 2018-04-27 03:32
Waiting for this.

**Comment by yannickcr** [comment] 2018-05-08 16:10
Fixed in #1681

**Comment by Hypnosphi** [comment] 2018-05-08 16:16
@yannickcr it still doesn't include `getSnapshotBeforeUpdate`

**Comment by ljharb** [comment] 2018-05-08 16:17
Reopening due to https://github.com/yannickcr/eslint-plugin-react/issues/1751#issuecomment-377501937

**Comment by dantman** [comment] 2018-05-08 17:03
The PR also appears to test for the version of react to enable the new lifecycle hooks. However remember that some code uses `react-lifecycles-compat` to polyfill them on older versions.

**Comment by ljharb** [comment] 2018-05-08 17:16
Hm, that’s a fair point - however i think that if you’re doing that, it’s reasonable to require setting your version pragma to 16.3, since that’s what you’re simulating.

**Closed** 2018-05-08 19:53 UTC
Labels: enhancement, help wanted, react 16

**Comment by yannickcr** [comment] 2018-05-09 09:08
I hope in the next days.

**Comment by mrbinky3000** [comment] 2018-05-17 03:44
Just wondering if this has been released yet?  If so, was there a regression?  I'm still seeing this error with the following packages:

- "eslint": "^4.19.1",
- "eslint-config-airbnb": "^16.1.0",
- "eslint-plugin-react": "^7.8.2",
- "react": "^16.3.1",
- "react-dom": "^16.3.1",

Example of code:

```javascript
import React from 'react';
import PropTypes from 'prop-types';

export default class Example extends React.Component {
  static propTypes = {
    colorName: PropTypes.string.isRequired,
    ext: PropTypes.string.isRequired,
    // ... others
  }

  static getDerivedStateFromProps(nextProps, prevState) {
    const {
      colorName, ext,
    } = nextProps;

    // ... code where colorName and ext are used
  }

  // ... rest of class
}
```

**Comment by ljharb** [comment] 2018-05-17 03:55
@mrbinky3000 have you set your react version pragma to 16.3?

**Comment by mrbinky3000** [comment] 2018-05-17 14:13
eslintrc file in the project root foler
```
{
    // this left intentionally blank
}
```

eslintrc file in the folder that contains our react app
```
{
  "extends": [
    "airbnb"
  ],
  "settings": {
    "react": {
      "pragma": "React",
      "version": "16.3"
    },
  },
  "parser": "babel-eslint",
  "env": {
    "browser": true,
    "node": true
  },
  "plugins": [
    "react",
    "jsx-a11y"
  ],
  "rules" {
     ... a few rule tweaks, none dealing with unused props.
  }
  "globals": {
    "expect": true,
    "PRODUCTION": true,
    "VERSION": true,
  }
}
```

**Comment by mrbinky3000** [comment] 2018-05-17 15:38
I ran eslint with debug.  Does `Unknown node type "ClassProperty"` help?

```
eslint:cli-engine Processing /Users/blah/project/component/Example.jsx +70ms
eslint:cli-engine Linting /Users/blah/project/component/Example.jsx +0ms
eslint:config Constructing config file hierarchy for /Users/blah/project/component +70ms
eslint:config Using .eslintrc and package.json files +0ms
eslint:config Using config from cache +2ms
eslint:linter Linting code for /Users/blah/project/component/Example.jsx (pass 1) +2ms
eslint:traverser Unknown node type "ClassProperty": Estimated visitor keys ["type","start","end","loc","static","computed","key","variance","value","range"] +343ms
eslint:traverser Unknown node type "ClassProperty": Estimated visitor keys ["type","start","end","loc","static","computed","key","variance","value","range"] +2ms
eslint:traverser Unknown node type "ClassProperty": Estimated visitor keys ["type","start","end","loc","static","computed","key","variance","value","range"] +5ms
eslint:linter Generating fixed text for /Users/blah/project/component/Example.jsx (pass 1) +45ms
```

**Comment by mqklin** [comment] 2018-07-13 07:12
Works perfect for me! Thanks!

**Comment by canda** [comment] 2018-08-14 17:49
ups!
Yeah, I didn't have the version set on my .eslintrc
Thanks @ljharb !

**Comment by ljharb** [comment] 2018-10-24 15:43
@danielepiccone can you file that as a new issue?

**Comment by ljharb** [comment] 2018-10-25 02:29
That’s because the fix isn’t released yet.

**Comment by danielepiccone** [comment] 2018-10-25 13:38
Opened a new issue here https://github.com/yannickcr/eslint-plugin-react/issues/2028

**Comment by plysik** [comment] 2019-02-12 07:33
What's the status of this issue?

**Comment by ljharb** [comment] 2019-02-12 16:28
@plysik as you can see on this very page, the issue is closed with a commit, which means the fix is in master. As you can see from the [commit](https://github.com/yannickcr/eslint-plugin-react/commit/95199385fe51355c34723882743ee420deee8aaa), it’s been released since v7.8.

If you are having a problem, please file a new issue.

**Comment by plysik** [comment] 2019-02-13 07:34
I've missed that tag as I saw the post form 25 Oct 2018. I just need to update package. Thanks!
