### ISSUE TITLE
JSX open html tag flow with space 

### ISSUE THREAD

**Issue by seeliang** [yannickcr/eslint-plugin-react#257] opened 2015-10-19 08:29 UTC
it may not fully related to this, but i just found out that in React
if you render ```html <h1> {'here is my react demo'}</h1> ``` (with a space after ```html<h1>```), this will render a empty span, 

is there any rule to warning this? many thanks

**Comment by yannickcr** [comment] 2015-10-19 08:44
Duplicate of #191.

There is no rule for now, but I would accept a PR for this ;)

**Closed by yannickcr** 2015-10-19 08:44 UTC

**Comment by seeliang** [comment] 2015-10-21 10:39
thanks for the update
