### ISSUE TITLE
Build for master is broken

### ISSUE THREAD

**Issue by jseminck** [yannickcr/eslint-plugin-react#1286] opened 2017-07-05 17:46 UTC
Last build on travis (21hrs ago) was successful: https://travis-ci.org/yannickcr/eslint-plugin-react/builds/250125668

However, when I try to run tests on master I get two failures (see below). Not sure what is up? Some newer version of a dependency that got updated was my first guess, but I could not find which.

```
  2369 passing (7s)
  2 failing

  1) no-unused-vars valid
        /* eslint jsx-uses-vars: 1 */
        class HelloMessage {}
        <HelloMessage />
      :

      AssertionError: Should have no errors but had 1: [ { ruleId: null,
    fatal: true,
    severity: 2,
    source: '        <HelloMessage />',
    message: 'Parsing error: Unexpected token <',
    line: 4,
    column: 9 } ]
      + expected - actual

      -1
      +0

      at testValidTemplate (node_modules/eslint/lib/testers/rule-tester.js:415:20)
      at Context.RuleTester.it (node_modules/eslint/lib/testers/rule-tester.js:545:25)

  2) no-unused-vars valid
        /* eslint jsx-uses-vars: 1 */
        class HelloMessage {
          render() {
            var HelloMessage = <div>Hello</div>;
            return HelloMessage;
          }
        }
        <HelloMessage />
      :

      AssertionError: Should have no errors but had 1: [ { ruleId: null,
    fatal: true,
    severity: 2,
    source: '        <HelloMessage />',
    message: 'Parsing error: Unexpected token <',
    line: 9,
    column: 9 } ]
      + expected - actual

      -1
      +0

      at testValidTemplate (node_modules/eslint/lib/testers/rule-tester.js:415:20)
      at Context.RuleTester.it (node_modules/eslint/lib/testers/rule-tester.js:545:25)
```

To reproduce:

```shell
git clone https://github.com/yannickcr/eslint-plugin-react/
npm i
npm test
```

Also TravisCI PR builds are broken, e.g: https://travis-ci.org/yannickcr/eslint-plugin-react/builds/250443200?utm_source=github_status&utm_medium=notification

**Comment by ljharb** [comment] 2017-07-05 19:48
I can't reproduce that issue locally; I've reran the master build. If that passes, then it's not a transitive dependency being updated.

What version of node are you using?

**Comment by ljharb** [comment] 2017-07-05 19:59
Since the travis master build failed, this time I `rm -rf node_modules && npm install`, and now I can reproduce it.

**Comment by ljharb** [comment] 2017-07-05 21:44
Fixed by 65b746edb07080ac3a8c66cd12c532f1a1adc5cb

**Closed by ljharb** 2017-07-05 21:44 UTC

**Comment by jseminck** [comment] 2017-07-05 22:03
Nice. I suppose the issue was a release of acorn? https://www.npmjs.com/package/acorn (which is a dependency of espree).

What about introducing yarn or npm5 to generate a lockfile? (I believe npm5 also generates it by default, but haven't used it yet)

**Comment by ljharb** [comment] 2017-07-05 22:25
Absolutely not; only apps should have lockfiles, never published packages.
